# Generated by Django 5.2 on 2025-09-18 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0134_merge_20250917_1942'),
        ('api', '0135_backfill_organizationbilling'),
    ]

    operations = [
    ]
