# Generated by Django 5.2 on 2025-09-22 15:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0139_merge_20250919_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('release_env', models.CharField(help_text='Environment this configuration applies to (e.g., prod, staging, local).', max_length=32, unique=True)),
                ('live_mode', models.BooleanField(default=False, help_text='Whether this configuration should run Stripe in live mode.')),
                ('live_secret_key_encrypted', models.BinaryField(blank=True, null=True)),
                ('test_secret_key_encrypted', models.BinaryField(blank=True, null=True)),
                ('webhook_secret_encrypted', models.BinaryField(blank=True, null=True)),
                ('startup_price_id', models.CharField(blank=True, default='', max_length=128)),
                ('startup_additional_task_price_id', models.CharField(blank=True, default='', max_length=128)),
                ('startup_product_id', models.CharField(blank=True, default='', max_length=128)),
                ('org_team_product_id', models.CharField(blank=True, default='', max_length=128)),
                ('task_meter_id', models.CharField(blank=True, default='', max_length=128)),
                ('task_meter_event_name', models.CharField(blank=True, default='', max_length=128)),
                ('org_task_meter_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stripe Configuration',
                'verbose_name_plural': 'Stripe Configuration',
                'ordering': ['release_env'],
            },
        ),
    ]
