# Generated by Django 5.2 on 2025-09-25 19:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0142_remove_db_stripe_secret_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentallowlistinvite',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('slack', 'Slack'), ('discord', 'Discord'), ('web', 'Web'), ('other', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='commsallowlistentry',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('slack', 'Slack'), ('discord', 'Discord'), ('web', 'Web'), ('other', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='commsallowlistrequest',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('slack', 'Slack'), ('discord', 'Discord'), ('web', 'Web'), ('other', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='persistentagentcommsendpoint',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('slack', 'Slack'), ('discord', 'Discord'), ('web', 'Web'), ('other', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='persistentagentconversation',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('slack', 'Slack'), ('discord', 'Discord'), ('web', 'Web'), ('other', 'Other')], max_length=32),
        ),
        migrations.CreateModel(
            name='PersistentAgentWebSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_source', models.CharField(blank=True, max_length=32)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_sessions', to='api.persistentagent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_web_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['agent', 'last_seen_at'], name='pa_web_session_last_seen_idx')],
                'constraints': [models.UniqueConstraint(fields=('agent', 'user'), name='uniq_web_session_agent_user')],
            },
        ),
    ]
