# Generated by Django 5.2 on 2025-10-08 16:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models

from constants.plans import PlanNamesChoices


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0154_set_vision_defaults'),
    ]

    def _set_default_daily_limits(apps, schema_editor):  # pragma: no cover - data migration
        PersistentAgent = apps.get_model('api', 'PersistentAgent')
        UserBilling = apps.get_model('api', 'UserBilling')
        OrganizationBilling = apps.get_model('api', 'OrganizationBilling')

        free_value = PlanNamesChoices.FREE.value

        for agent in PersistentAgent.objects.filter(daily_credit_limit__isnull=True):
            plan_value = free_value

            if agent.organization_id:
                billing = OrganizationBilling.objects.filter(organization_id=agent.organization_id).only('subscription').first()
                if billing and billing.subscription:
                    plan_value = billing.subscription
            else:
                billing = UserBilling.objects.filter(user_id=agent.user_id).only('subscription').first()
                if billing and billing.subscription:
                    plan_value = billing.subscription

            if plan_value == free_value:
                agent.daily_credit_limit = Decimal('10')
                agent.save(update_fields=['daily_credit_limit'])

    def _noop(apps, schema_editor):  # pragma: no cover - reverse noop
        return

    operations = [
        migrations.AddField(
            model_name='persistentagent',
            name='daily_credit_limit',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Maximum task credits this agent may consume per day. Null means unlimited.', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='PersistentAgentDailyCreditUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateField()),
                ('credits_used', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_credit_usages', to='api.persistentagent')),
            ],
            options={
                'indexes': [models.Index(fields=['agent', 'usage_date'], name='pa_daily_usage_idx')],
                'unique_together': {('agent', 'usage_date')},
            },
        ),
        migrations.RunPython(_set_default_daily_limits, _noop),
    ]
