# Generated by Django 5.2 on 2025-10-19 18:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0165_browseruseagenttask_webhook_last_called_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersistentAgentSmsGroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=32)),
                ('display_name', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersistentAgentSmsGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Label shown in the console for this group.', max_length=128)),
                ('twilio_conversation_sid', models.CharField(blank=True, help_text='Backing Twilio Conversation SID for this group, if provisioned.', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_groups', to='api.persistentagent')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='persistentagentconversation',
            name='sms_group',
            field=models.ForeignKey(blank=True, help_text='When set, this conversation maps to a saved SMS group.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='api.persistentagentsmsgroup'),
        ),
        migrations.AddIndex(
            model_name='persistentagentconversation',
            index=models.Index(fields=['sms_group'], name='pa_conv_sms_group_idx'),
        ),
        migrations.AddField(
            model_name='persistentagentsmsgroupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.persistentagentsmsgroup'),
        ),
        migrations.AddIndex(
            model_name='persistentagentsmsgroup',
            index=models.Index(fields=['agent', 'is_active'], name='pa_sms_group_agent_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='persistentagentsmsgroup',
            unique_together={('agent', 'name')},
        ),
        migrations.AddIndex(
            model_name='persistentagentsmsgroupmember',
            index=models.Index(fields=['group'], name='pa_sms_group_member_group_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='persistentagentsmsgroupmember',
            unique_together={('group', 'phone_number')},
        ),
    ]
