# Generated by Django 5.2 on 2025-10-26 18:00

from django.db import migrations


class Migration(migrations.Migration):
    # This merge migration reconnects 0131 into the main chain without breaking
    # environments that already applied the later 0170 migration.

    dependencies = [
        ('api', '0131_seed_pretrained_worker_templates'),
        ('api', '0170_embeddingsmodelendpoint_embeddingsllmtier_and_more'),
    ]

    operations = []
