# Generated by Django 5.2 on 2025-10-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0172_mcp_oauth_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentagent',
            name='avatar_generated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent successful avatar generation.', null=True),
        ),
        migrations.AddField(
            model_name='persistentagent',
            name='avatar_generation_requested_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when avatar generation was requested.', null=True),
        ),
        migrations.AddField(
            model_name='persistentagent',
            name='avatar_storage_path',
            field=models.CharField(blank=True, help_text='Storage path for the generated avatar image.', max_length=512),
        ),
    ]
