# Generated by Django 5.2 on 2025-10-30 17:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0173_persistentagent_mini_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersistentPremiumLLMTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(help_text='1-based order within the premium range')),
                ('description', models.CharField(blank=True, max_length=256)),
                ('token_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_tiers', to='api.persistenttokenrange')),
            ],
            options={
                'ordering': ['token_range__min_tokens', 'order'],
                'unique_together': {('token_range', 'order')},
            },
        ),
        migrations.CreateModel(
            name='PersistentPremiumTierEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.FloatField(help_text='Relative weight within the premium tier; > 0')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_premium_tiers', to='api.persistentmodelendpoint')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_endpoints', to='api.persistentpremiumllmtier')),
            ],
            options={
                'ordering': ['tier__order', 'endpoint__key'],
                'unique_together': {('tier', 'endpoint')},
            },
        ),
        migrations.CreateModel(
            name='BrowserPremiumLLMTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(help_text='1-based order within the premium policy')),
                ('description', models.CharField(blank=True, max_length=256)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_tiers', to='api.browserllmpolicy')),
            ],
            options={
                'ordering': ['policy__name', 'order'],
                'unique_together': {('policy', 'order')},
            },
        ),
        migrations.CreateModel(
            name='BrowserPremiumTierEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.FloatField(help_text='Relative weight within the premium tier; > 0')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_premium_tiers', to='api.browsermodelendpoint')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_endpoints', to='api.browserpremiumllmtier')),
            ],
            options={
                'ordering': ['tier__order', 'endpoint__key'],
                'unique_together': {('tier', 'endpoint')},
            },
        ),
    ]
