# Generated by Django 5.2 on 2025-11-05 14:42

import django.db.models.deletion
import uuid
from django.db import migrations, models
from django.db.models import Case, When, Value


def backfill_step_completions(apps, schema_editor):
    Step = apps.get_model("api", "PersistentAgentStep")
    Completion = apps.get_model("api", "PersistentAgentCompletion")
    db_alias = schema_editor.connection.alias
    token_filter = (
        models.Q(prompt_tokens__isnull=False)
        | models.Q(completion_tokens__isnull=False)
        | models.Q(total_tokens__isnull=False)
        | models.Q(cached_tokens__isnull=False)
        | models.Q(llm_model__isnull=False)
        | models.Q(llm_provider__isnull=False)
    )
    step_fields = [
        "id",
        "agent_id",
        "created_at",
        "prompt_tokens",
        "completion_tokens",
        "total_tokens",
        "cached_tokens",
        "llm_model",
        "llm_provider",
    ]
    steps = (
        Step.objects.using(db_alias)
        .filter(token_filter, completion__isnull=True)
        .order_by("agent_id", "created_at", "id")
        .values(*step_fields)
    )

    current_group = []
    current_key = None
    pending_completions = []
    pending_step_pairs = []  # (step_id, completion_uuid)
    pending_step_ids = []
    BATCH_SIZE = 500

    def persist_batch():
        nonlocal pending_completions, pending_step_pairs, pending_step_ids
        if not pending_step_pairs:
            return
        Completion.objects.using(db_alias).bulk_create(pending_completions, batch_size=BATCH_SIZE)
        case_expr = Case(
            *[When(pk=step_id, then=Value(completion_id)) for step_id, completion_id in pending_step_pairs],
            output_field=models.UUIDField(),
        )
        Step.objects.using(db_alias).filter(pk__in=pending_step_ids).update(completion=case_expr)
        pending_completions = []
        pending_step_pairs = []
        pending_step_ids = []

    def queue_group(group):
        if not group:
            return
        completion_id = uuid.uuid4()
        first = group[0]
        pending_completions.append(
            Completion(
                id=completion_id,
                agent_id=first["agent_id"],
                prompt_tokens=first["prompt_tokens"],
                completion_tokens=first["completion_tokens"],
                total_tokens=first["total_tokens"],
                cached_tokens=first["cached_tokens"],
                llm_model=first["llm_model"],
                llm_provider=first["llm_provider"],
                billed=True,
                billed_at=first["created_at"],
            )
        )
        for step in group:
            pending_step_pairs.append((step["id"], completion_id))
            pending_step_ids.append(step["id"])
        if len(pending_step_ids) >= BATCH_SIZE:
            persist_batch()

    for step in steps.iterator(chunk_size=2000):
        key = (
            step["agent_id"],
            step["prompt_tokens"],
            step["completion_tokens"],
            step["total_tokens"],
            step["cached_tokens"],
            step["llm_model"],
            step["llm_provider"],
        )
        if not current_group:
            current_group = [step]
            current_key = key
            continue
        if key == current_key:
            current_group.append(step)
            continue
        queue_group(current_group)
        current_group = [step]
        current_key = key

    queue_group(current_group)
    persist_batch()


def revert_step_completions(apps, schema_editor):
    Step = apps.get_model("api", "PersistentAgentStep")
    Completion = apps.get_model("api", "PersistentAgentCompletion")
    db_alias = schema_editor.connection.alias
    completion_fields = [
        "id",
        "prompt_tokens",
        "completion_tokens",
        "total_tokens",
        "cached_tokens",
        "llm_model",
        "llm_provider",
    ]
    completions = Completion.objects.using(db_alias).values(*completion_fields).iterator(chunk_size=2000)
    for completion in completions:
        step_updates = {
            "prompt_tokens": completion["prompt_tokens"],
            "completion_tokens": completion["completion_tokens"],
            "total_tokens": completion["total_tokens"],
            "cached_tokens": completion["cached_tokens"],
            "llm_model": completion["llm_model"],
            "llm_provider": completion["llm_provider"],
        }
        Step.objects.using(db_alias).filter(completion_id=completion["id"]).update(**step_updates)

    Step.objects.using(db_alias).update(completion=None)
    Completion.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('api', '0178_merge_20251104_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersistentAgentCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('completion_tokens', models.IntegerField(blank=True, null=True)),
                ('total_tokens', models.IntegerField(blank=True, null=True)),
                ('cached_tokens', models.IntegerField(blank=True, null=True)),
                ('llm_model', models.CharField(blank=True, max_length=256, null=True)),
                ('llm_provider', models.CharField(blank=True, max_length=128, null=True)),
                ('credits_cost', models.DecimalField(blank=True, decimal_places=3, help_text='Credits consumed for this completion (if charged).', max_digits=12, null=True)),
                ('billed', models.BooleanField(default=False, help_text='True once credits were consumed for this completion.')),
                ('billed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(help_text='Agent that triggered this LLM completion.', on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='api.persistentagent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='persistentagentstep',
            name='completion',
            field=models.ForeignKey(blank=True, help_text='LLM completion that produced this step (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='api.persistentagentcompletion'),
        ),
        migrations.AddIndex(
            model_name='persistentagentcompletion',
            index=models.Index(fields=['agent', '-created_at'], name='pa_completion_recent_idx'),
        ),
        migrations.RunPython(backfill_step_completions, revert_step_completions),
    ]
