# Generated by Django 5.2 on 2025-11-05 14:42

import django.db.models.deletion
import uuid

from django.db import migrations, models


def backfill_step_completions(apps, schema_editor):
    token_filter_sql = "(" + " OR ".join([
        "prompt_tokens IS NOT NULL",
        "completion_tokens IS NOT NULL",
        "total_tokens IS NOT NULL",
        "cached_tokens IS NOT NULL",
        "llm_model IS NOT NULL",
        "llm_provider IS NOT NULL",
    ]) + ")"

    schema_editor.execute(
        """
        CREATE TEMP TABLE tmp_pa_step_completion (
            step_id UUID PRIMARY KEY,
            completion_id UUID,
            agent_id UUID,
            created_at TIMESTAMPTZ,
            prompt_tokens INTEGER,
            completion_tokens INTEGER,
            total_tokens INTEGER,
            cached_tokens INTEGER,
            llm_model VARCHAR(256),
            llm_provider VARCHAR(128)
        )
        """
    )

    schema_editor.execute(
        f"""
        INSERT INTO tmp_pa_step_completion (
            step_id,
            completion_id,
            agent_id,
            created_at,
            prompt_tokens,
            completion_tokens,
            total_tokens,
            cached_tokens,
            llm_model,
            llm_provider
        )
        WITH ordered AS (
            SELECT
                id AS step_id,
                agent_id,
                created_at,
                prompt_tokens,
                completion_tokens,
                total_tokens,
                cached_tokens,
                llm_model,
                llm_provider,
                CASE
                    WHEN LAG(id) OVER w IS NULL THEN 1
                    WHEN LAG(prompt_tokens) OVER w IS DISTINCT FROM prompt_tokens THEN 1
                    WHEN LAG(completion_tokens) OVER w IS DISTINCT FROM completion_tokens THEN 1
                    WHEN LAG(total_tokens) OVER w IS DISTINCT FROM total_tokens THEN 1
                    WHEN LAG(cached_tokens) OVER w IS DISTINCT FROM cached_tokens THEN 1
                    WHEN LAG(llm_model) OVER w IS DISTINCT FROM llm_model THEN 1
                    WHEN LAG(llm_provider) OVER w IS DISTINCT FROM llm_provider THEN 1
                    ELSE 0
                END AS new_group
            FROM api_persistentagentstep
            WHERE completion_id IS NULL AND {token_filter_sql}
            WINDOW w AS (PARTITION BY agent_id ORDER BY created_at, id)
        ), grouped AS (
            SELECT
                ordered.*,
                SUM(new_group) OVER (
                    PARTITION BY agent_id
                    ORDER BY created_at, step_id
                    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
                ) AS group_seq
            FROM ordered
        )
        SELECT
            step_id,
            (MIN(step_id::text) OVER (PARTITION BY agent_id, group_seq))::uuid AS completion_id,
            agent_id,
            created_at,
            prompt_tokens,
            completion_tokens,
            total_tokens,
            cached_tokens,
            llm_model,
            llm_provider
        FROM grouped
        """
    )

    schema_editor.execute(
        """
        INSERT INTO api_persistentagentcompletion (
            id,
            agent_id,
            created_at,
            prompt_tokens,
            completion_tokens,
            total_tokens,
            cached_tokens,
            llm_model,
            llm_provider,
            billed,
            billed_at
        )
        SELECT
            completion_id,
            agent_id,
            MIN(created_at) AS created_at,
            prompt_tokens,
            completion_tokens,
            total_tokens,
            cached_tokens,
            llm_model,
            llm_provider,
            TRUE,
            MIN(created_at) AS billed_at
        FROM tmp_pa_step_completion
        GROUP BY
            completion_id,
            agent_id,
            prompt_tokens,
            completion_tokens,
            total_tokens,
            cached_tokens,
            llm_model,
            llm_provider
        ON CONFLICT (id) DO NOTHING
        """
    )

    schema_editor.execute(
        """
        UPDATE api_persistentagentstep AS step
        SET completion_id = tmp.completion_id
        FROM tmp_pa_step_completion AS tmp
        WHERE step.id = tmp.step_id
        """
    )

    schema_editor.execute("DROP TABLE IF EXISTS tmp_pa_step_completion")


def revert_step_completions(apps, schema_editor):
    schema_editor.execute(
        """
        UPDATE api_persistentagentstep AS step
        SET
            prompt_tokens = completion.prompt_tokens,
            completion_tokens = completion.completion_tokens,
            total_tokens = completion.total_tokens,
            cached_tokens = completion.cached_tokens,
            llm_model = completion.llm_model,
            llm_provider = completion.llm_provider
        FROM api_persistentagentcompletion AS completion
        WHERE step.completion_id = completion.id
        """
    )

    schema_editor.execute("UPDATE api_persistentagentstep SET completion_id = NULL")
    schema_editor.execute("DELETE FROM api_persistentagentcompletion")


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('api', '0178_merge_20251104_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersistentAgentCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('completion_tokens', models.IntegerField(blank=True, null=True)),
                ('total_tokens', models.IntegerField(blank=True, null=True)),
                ('cached_tokens', models.IntegerField(blank=True, null=True)),
                ('llm_model', models.CharField(blank=True, max_length=256, null=True)),
                ('llm_provider', models.CharField(blank=True, max_length=128, null=True)),
                ('credits_cost', models.DecimalField(blank=True, decimal_places=3, help_text='Credits consumed for this completion (if charged).', max_digits=12, null=True)),
                ('billed', models.BooleanField(default=False, help_text='True once credits were consumed for this completion.')),
                ('billed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(help_text='Agent that triggered this LLM completion.', on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='api.persistentagent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='persistentagentstep',
            name='completion',
            field=models.ForeignKey(blank=True, help_text='LLM completion that produced this step (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='api.persistentagentcompletion'),
        ),
        migrations.AddIndex(
            model_name='persistentagentcompletion',
            index=models.Index(fields=['agent', '-created_at'], name='pa_completion_recent_idx'),
        ),
        migrations.RunPython(backfill_step_completions, revert_step_completions),
    ]
