# Generated by Django 5.2 on 2025-11-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0179_persistentagentcompletion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persistentagentstep',
            name='cached_tokens',
        ),
        migrations.RemoveField(
            model_name='persistentagentstep',
            name='completion_tokens',
        ),
        migrations.RemoveField(
            model_name='persistentagentstep',
            name='llm_model',
        ),
        migrations.RemoveField(
            model_name='persistentagentstep',
            name='llm_provider',
        ),
        migrations.RemoveField(
            model_name='persistentagentstep',
            name='prompt_tokens',
        ),
        migrations.RemoveField(
            model_name='persistentagentstep',
            name='total_tokens',
        ),
    ]
