# Generated by Django 5.2 on 2025-12-02 15:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0216_alter_persistentagentsystemstep_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersistentAgentVariable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Unique variable name within an agent.', max_length=128)),
                ('value', models.TextField(help_text='Raw value as text (JSON-encoded when structured).')),
                ('is_json', models.BooleanField(default=False, help_text='True when value is JSON-encoded structured data.')),
                ('size_bytes', models.PositiveIntegerField(default=0, help_text='Size of value in bytes for budgeting.')),
                ('summary', models.CharField(blank=True, help_text='Optional short description of the variable contents.', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(help_text='Agent that owns this variable.', on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='api.persistentagent')),
                ('tool_call', models.ForeignKey(blank=True, help_text='Originating tool call, when applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variables', to='api.persistentagenttoolcall')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', '-created_at'], name='pa_variable_recent_idx'), models.Index(fields=['agent', 'name'], name='pa_variable_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('agent', 'name'), name='pa_variable_agent_name_unique')],
            },
        ),
    ]
