# Generated by Codex

from django.db import migrations


def add_google_drive_prefetch(apps, schema_editor):
    """Ensure pipedream prefetch_apps includes google_drive."""
    MCPServerConfig = apps.get_model("api", "MCPServerConfig")

    for cfg in MCPServerConfig.objects.filter(name="pipedream"):
        prefetch = list(cfg.prefetch_apps or [])
        if "google_drive" not in prefetch:
            prefetch.append("google_drive")
            cfg.prefetch_apps = prefetch
            cfg.save(update_fields=["prefetch_apps"])


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0246_add_google_docs_to_pipedream_prefetch"),
    ]

    operations = [
        migrations.RunPython(add_google_drive_prefetch, migrations.RunPython.noop),
    ]
