# Generated by Django 5.2 on 2026-01-07 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0250_google_workspace_credentials'),
        ('api', '0255_plan_version_price_shared_ids'),
    ]

    operations = [
    ]
