# Generated by Django 5.2 on 2026-01-19 16:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0261_pipedreamconnectsession_nullable_connect_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTaskConfig',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('max_work_task_steps', models.PositiveIntegerField(default=8, help_text='Maximum LLM steps per work task; set to 0 to use the system default.')),
                ('max_work_task_tool_calls', models.PositiveIntegerField(default=12, help_text='Maximum tool calls per work task; set to 0 for unlimited.')),
                ('max_work_tasks_per_day', models.PositiveIntegerField(default=100, help_text='Maximum work tasks that can start each day; set to 0 for unlimited.')),
                ('max_active_work_tasks', models.PositiveIntegerField(default=5, help_text='Maximum concurrently active work tasks; set to 0 for unlimited.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Work task configuration',
                'verbose_name_plural': 'Work task configuration',
            },
        ),
        migrations.CreateModel(
            name='WorkTaskLLMTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(help_text='1-based order across all work task tiers.', unique=True)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('result_summary', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('prompt_tokens', models.IntegerField(blank=True, help_text="Number of tokens used in the prompt for this work task's LLM call(s).", null=True)),
                ('completion_tokens', models.IntegerField(blank=True, help_text="Number of tokens generated in the completion for this work task's LLM call(s).", null=True)),
                ('total_tokens', models.IntegerField(blank=True, help_text="Total tokens used (prompt + completion) for this work task's LLM call(s).", null=True)),
                ('credits_cost', models.DecimalField(blank=True, decimal_places=3, help_text='Credits charged for this work task; defaults to configured per-task cost.', max_digits=12, null=True)),
                ('cached_tokens', models.IntegerField(blank=True, help_text='Number of cached tokens used (if provider supports caching).', null=True)),
                ('input_cost_total', models.DecimalField(blank=True, decimal_places=6, help_text='Total USD cost for prompt tokens (cached + uncached).', max_digits=12, null=True)),
                ('input_cost_uncached', models.DecimalField(blank=True, decimal_places=6, help_text='USD cost for uncached prompt tokens.', max_digits=12, null=True)),
                ('input_cost_cached', models.DecimalField(blank=True, decimal_places=6, help_text='USD cost for cached prompt tokens.', max_digits=12, null=True)),
                ('output_cost', models.DecimalField(blank=True, decimal_places=6, help_text='USD cost for completion tokens.', max_digits=12, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=6, help_text='Total USD cost (input + output).', max_digits=12, null=True)),
                ('llm_model', models.CharField(blank=True, help_text='LLM model used for this work task.', max_length=256, null=True)),
                ('llm_provider', models.CharField(blank=True, help_text='LLM provider used for this work task.', max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metered', models.BooleanField(db_index=True, default=False, help_text='Marked true once included in Stripe metering rollup.')),
                ('meter_batch_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_tasks', to='api.persistentagent')),
                ('eval_run', models.ForeignKey(blank=True, help_text='Eval run that spawned this work task, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_tasks', to='api.evalrun')),
                ('organization', models.ForeignKey(blank=True, help_text='Owning organization, when applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_tasks', to='api.organization')),
                ('task_credit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_tasks', to='api.taskcredit')),
                ('tool_call_step', models.OneToOneField(blank=True, help_text='Tool call step that spawned this work task, for tool result preview updates.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_task', to='api.persistentagentstep')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkTaskModelEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(help_text="Endpoint key, e.g., 'openai_gpt4o_mini_work_task'", max_length=96, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('low_latency', models.BooleanField(default=False, help_text='Marks this endpoint as low latency/high performance.')),
                ('litellm_model', models.CharField(help_text='Model identifier passed to LiteLLM.', max_length=256)),
                ('api_base', models.CharField(blank=True, help_text='Optional OpenAI-compatible base URL for proxy endpoints.', max_length=256)),
                ('supports_temperature', models.BooleanField(default=True, help_text='Indicates whether this model accepts a temperature parameter.')),
                ('supports_tool_choice', models.BooleanField(default=True, help_text='Indicates whether this model accepts tool_choice.')),
                ('use_parallel_tool_calls', models.BooleanField(default=True, help_text='Hint to allow parallel tool calls when supported by the provider.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(blank=True, help_text='Optional link to the provider supplying credentials for this endpoint.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_task_endpoints', to='api.llmprovider')),
            ],
            options={
                'ordering': ['provider__display_name', 'litellm_model'],
            },
        ),
        migrations.CreateModel(
            name='WorkTaskStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.PositiveIntegerField()),
                ('tool_name', models.CharField(max_length=256)),
                ('tool_params', models.JSONField(blank=True, null=True)),
                ('tool_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.worktask')),
            ],
            options={
                'ordering': ['task', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='WorkTaskTierEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.FloatField(help_text='Relative weight within the tier; must be > 0.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_tiers', to='api.worktaskmodelendpoint')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_endpoints', to='api.worktaskllmtier')),
            ],
            options={
                'ordering': ['tier__order', 'endpoint__key'],
            },
        ),
        migrations.AddIndex(
            model_name='worktask',
            index=models.Index(fields=['status', 'created_at'], name='work_task_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='worktask',
            index=models.Index(fields=['created_at'], name='work_task_created_idx'),
        ),
        migrations.AddIndex(
            model_name='worktask',
            index=models.Index(fields=['organization', 'created_at'], name='work_task_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='worktaskmodelendpoint',
            index=models.Index(fields=['key'], name='api_worktas_key_9337f7_idx'),
        ),
        migrations.AddIndex(
            model_name='worktaskmodelendpoint',
            index=models.Index(fields=['enabled'], name='api_worktas_enabled_e15559_idx'),
        ),
        migrations.AddIndex(
            model_name='worktaskmodelendpoint',
            index=models.Index(fields=['provider'], name='api_worktas_provide_0ce5c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='worktaskstep',
            constraint=models.UniqueConstraint(fields=('task', 'step_number'), name='unique_work_task_step_task_step_number'),
        ),
        migrations.AlterUniqueTogether(
            name='worktasktierendpoint',
            unique_together={('tier', 'endpoint')},
        ),
    ]
