# Generated by Django 5.2 on 2026-01-26 14:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0270_alter_userattribution_referrer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persistentagent',
            name='whitelist_policy',
            field=models.CharField(choices=[('default', 'Default (Owner or Org Members)'), ('manual', 'Allowed Contacts List'), ('blocklist', 'Blocklist (Outbound Allow All)')], default='manual', help_text="Controls who can message this agent and who the agent may contact. Manual: only addresses/numbers listed on the agent's allowlist (includes owner/org members by default). Blocklist: outbound is allowed for all contacts unless explicitly blocked; inbound still requires approval.", max_length=16),
        ),
        migrations.CreateModel(
            name='CommsBlocklistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('slack', 'Slack'), ('discord', 'Discord'), ('web', 'Web Chat'), ('other', 'Other')], max_length=32)),
                ('address', models.CharField(help_text='Email address or E.164 phone number', max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('block_inbound', models.BooleanField(default=True, help_text='Whether this contact is blocked from sending messages to the agent')),
                ('block_outbound', models.BooleanField(default=True, help_text='Whether the agent is blocked from sending messages to this contact')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(help_text='Agent to which this blocklist entry applies', on_delete=django.db.models.deletion.CASCADE, related_name='manual_blocklist', to='api.persistentagent')),
            ],
            options={
                'ordering': ['channel', 'address'],
                'indexes': [models.Index(fields=['agent', 'channel'], name='block_agent_channel_idx')],
                'constraints': [models.UniqueConstraint(fields=('agent', 'channel', 'address'), name='uniq_blocklist_agent_channel_address')],
            },
        ),
        migrations.CreateModel(
            name='CommsOutboundContactUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('slack', 'Slack'), ('discord', 'Discord'), ('web', 'Web Chat'), ('other', 'Other')], max_length=32)),
                ('address', models.CharField(max_length=512)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('first_used_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_contact_usage', to='api.persistentagent')),
            ],
            options={
                'ordering': ['-last_used_at'],
                'indexes': [models.Index(fields=['agent', 'channel', 'period_start'], name='usage_agent_channel_period_idx'), models.Index(fields=['agent', 'period_start'], name='usage_agent_period_idx')],
                'constraints': [models.UniqueConstraint(fields=('agent', 'channel', 'address', 'period_start'), name='uniq_contact_usage_agent_channel_address_period')],
            },
        ),
    ]
