# Generated by Django 5.2 on 2026-02-02 16:30

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0279_rename_service_partner_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummarizationModelEndpoint',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('key', models.SlugField(max_length=96, unique=True, help_text="Endpoint key, e.g., 'openai_gpt4o_summary'")),
                ('enabled', models.BooleanField(default=True)),
                ('low_latency', models.BooleanField(default=False, help_text='Marks this endpoint as low latency/high performance.')),
                ('litellm_model', models.CharField(max_length=256, help_text='Model identifier passed to LiteLLM.')),
                ('api_base', models.CharField(max_length=256, blank=True, help_text='Optional OpenAI-compatible base URL for proxy endpoints.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'provider',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='summarization_endpoints',
                        help_text='Optional link to the provider supplying credentials for this endpoint.',
                        to='api.llmprovider',
                    ),
                ),
            ],
            options={
                'ordering': ['provider__display_name', 'litellm_model'],
            },
        ),
        migrations.CreateModel(
            name='SummarizationLLMTier',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('order', models.PositiveIntegerField(unique=True, help_text='1-based order across all summarization tiers.')),
                ('description', models.CharField(max_length=256, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SummarizationTierEndpoint',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('weight', models.FloatField(help_text='Relative weight within the tier; must be > 0.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'endpoint',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='in_tiers',
                        to='api.summarizationmodelendpoint',
                    ),
                ),
                (
                    'tier',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tier_endpoints',
                        to='api.summarizationllmtier',
                    ),
                ),
            ],
            options={
                'ordering': ['tier__order', 'endpoint__key'],
                'unique_together': {('tier', 'endpoint')},
            },
        ),
        migrations.AddIndex(
            model_name='summarizationmodelendpoint',
            index=models.Index(fields=['key'], name='api_summa_key_24e3f4_idx'),
        ),
        migrations.AddIndex(
            model_name='summarizationmodelendpoint',
            index=models.Index(fields=['enabled'], name='api_summa_enabl_5c2d21_idx'),
        ),
        migrations.AddIndex(
            model_name='summarizationmodelendpoint',
            index=models.Index(fields=['provider'], name='api_summa_provi_3d5b9f_idx'),
        ),
    ]
