# Generated by Django 6.0 on 2026-02-26 20:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0296_userattribution_reddit_click_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseLLMTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(help_text='1-based order across all database tiers.', unique=True)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseModelEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(help_text="Endpoint key, e.g., 'openrouter_gpt41_db'", max_length=96, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('low_latency', models.BooleanField(default=False, help_text='Marks this endpoint as low latency/high performance.')),
                ('litellm_model', models.CharField(help_text='Model identifier passed to LiteLLM.', max_length=256)),
                ('api_base', models.CharField(blank=True, help_text='Optional OpenAI-compatible base URL for proxy endpoints.', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(blank=True, help_text='Optional link to the provider supplying credentials for this endpoint.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='database_endpoints', to='api.llmprovider')),
            ],
            options={
                'ordering': ['provider__display_name', 'litellm_model'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseTierEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.FloatField(help_text='Relative weight within the tier; must be > 0.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_tiers', to='api.databasemodelendpoint')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_endpoints', to='api.databasellmtier')),
            ],
            options={
                'ordering': ['tier__order', 'endpoint__key'],
                'unique_together': {('tier', 'endpoint')},
            },
        ),
        migrations.AddIndex(
            model_name='databasemodelendpoint',
            index=models.Index(fields=['key'], name='api_databas_key_f22f38_idx'),
        ),
        migrations.AddIndex(
            model_name='databasemodelendpoint',
            index=models.Index(fields=['enabled'], name='api_databas_enabled_851580_idx'),
        ),
        migrations.AddIndex(
            model_name='databasemodelendpoint',
            index=models.Index(fields=['provider'], name='api_databas_provide_fd31c1_idx'),
        ),
    ]
