# Generated by Django 6.0 on 2026-03-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0319_persistentagenthumaninputrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commsallowlistrequest',
            name='approval_token',
            field=models.CharField(blank=True, help_text='Unique token for one-click email approval', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='commsallowlistrequest',
            name='denial_token',
            field=models.CharField(blank=True, help_text='Unique token for one-click email denial', max_length=64, null=True, unique=True),
        ),
    ]
