# Generated by Django 6.0 on 2026-04-06 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0321_persistentagentwebsession_visibility_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="persistentagentsecret",
            name="unique_agent_type_domain_secret_name",
        ),
        migrations.RemoveConstraint(
            model_name="persistentagentsecret",
            name="unique_agent_type_domain_secret_key",
        ),
        migrations.AddField(
            model_name="persistentagentsecret",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="global_secrets",
                to="api.organization",
            ),
        ),
        migrations.AddField(
            model_name="persistentagentsecret",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="global_secrets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="persistentagentsecret",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="secrets",
                to="api.persistentagent",
            ),
        ),
        migrations.AddIndex(
            model_name="persistentagentsecret",
            index=models.Index(fields=["user"], name="pa_secret_user_idx"),
        ),
        migrations.AddIndex(
            model_name="persistentagentsecret",
            index=models.Index(fields=["organization"], name="pa_secret_org_idx"),
        ),
        migrations.AddConstraint(
            model_name="persistentagentsecret",
            constraint=models.UniqueConstraint(
                condition=models.Q(("agent__isnull", False)),
                fields=("agent", "secret_type", "domain_pattern", "name"),
                name="unique_agent_type_domain_secret_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="persistentagentsecret",
            constraint=models.UniqueConstraint(
                condition=models.Q(("agent__isnull", False)),
                fields=("agent", "secret_type", "domain_pattern", "key"),
                name="unique_agent_type_domain_secret_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="persistentagentsecret",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("organization__isnull", True), ("user__isnull", False)
                ),
                fields=("user", "secret_type", "domain_pattern", "name"),
                name="unique_user_type_domain_secret_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="persistentagentsecret",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("organization__isnull", True), ("user__isnull", False)
                ),
                fields=("user", "secret_type", "domain_pattern", "key"),
                name="unique_user_type_domain_secret_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="persistentagentsecret",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organization__isnull", False)),
                fields=("organization", "secret_type", "domain_pattern", "name"),
                name="unique_org_type_domain_secret_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="persistentagentsecret",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organization__isnull", False)),
                fields=("organization", "secret_type", "domain_pattern", "key"),
                name="unique_org_type_domain_secret_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="persistentagentsecret",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("agent__isnull", False),
                        ("user__isnull", True),
                        ("organization__isnull", True),
                    ),
                    models.Q(
                        ("agent__isnull", True),
                        ("user__isnull", False),
                        ("organization__isnull", True),
                    ),
                    models.Q(
                        ("agent__isnull", True),
                        ("user__isnull", True),
                        ("organization__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="secret_exactly_one_owner",
            ),
        ),
    ]
