# Generated by Django 6.0 on 2026-04-06 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0321_persistentagentwebsession_visibility_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="persistentagentsecret",
            name="unique_agent_type_domain_secret_name",
        ),
        migrations.RemoveConstraint(
            model_name="persistentagentsecret",
            name="unique_agent_type_domain_secret_key",
        ),
        migrations.AddField(
            model_name="persistentagentsecret",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning organization for global secrets.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="global_secrets",
                to="api.organization",
            ),
        ),
        migrations.AddField(
            model_name="persistentagentsecret",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning user for global secrets (when no organization).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="global_secrets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="persistentagentsecret",
            name="visibility",
            field=models.CharField(
                choices=[("agent", "Agent"), ("global", "Global")],
                default="agent",
                help_text="Whether this secret is agent-scoped or globally shared.",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="persistentagentsecret",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning agent. Null for global secrets.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="secrets",
                to="api.persistentagent",
            ),
        ),
        migrations.AddIndex(
            model_name="persistentagentsecret",
            index=models.Index(
                fields=["user", "visibility"], name="pa_secret_user_vis_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="persistentagentsecret",
            index=models.Index(
                fields=["organization", "visibility"], name="pa_secret_org_vis_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="persistentagentsecret",
            constraint=models.UniqueConstraint(
                condition=models.Q(("visibility", "agent")),
                fields=("agent", "secret_type", "domain_pattern", "name"),
                name="unique_agent_type_domain_secret_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="persistentagentsecret",
            constraint=models.UniqueConstraint(
                condition=models.Q(("visibility", "agent")),
                fields=("agent", "secret_type", "domain_pattern", "key"),
                name="unique_agent_type_domain_secret_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="persistentagentsecret",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("organization__isnull", True), ("visibility", "global")
                ),
                fields=("user", "secret_type", "domain_pattern", "name"),
                name="unique_global_user_type_domain_secret_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="persistentagentsecret",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("organization__isnull", True), ("visibility", "global")
                ),
                fields=("user", "secret_type", "domain_pattern", "key"),
                name="unique_global_user_type_domain_secret_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="persistentagentsecret",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("organization__isnull", False), ("visibility", "global")
                ),
                fields=("organization", "secret_type", "domain_pattern", "name"),
                name="unique_global_org_type_domain_secret_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="persistentagentsecret",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("organization__isnull", False), ("visibility", "global")
                ),
                fields=("organization", "secret_type", "domain_pattern", "key"),
                name="unique_global_org_type_domain_secret_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="persistentagentsecret",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("agent__isnull", False), ("visibility", "agent")),
                    models.Q(("agent__isnull", True), ("visibility", "global")),
                    _connector="OR",
                ),
                name="secret_visibility_agent_integrity",
            ),
        ),
        migrations.AddConstraint(
            model_name="persistentagentsecret",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("visibility", "agent"),
                    models.Q(
                        ("visibility", "global"),
                        models.Q(
                            ("user__isnull", False),
                            ("organization__isnull", False),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="secret_global_must_have_owner",
            ),
        ),
    ]
