# Generated by Django 6.0 on 2026-04-03 17:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0333_globalagentskill_and_agentskill_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NativeAppSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token_hash', models.CharField(max_length=64)),
                ('refresh_token_hash', models.CharField(max_length=64)),
                ('access_expires_at', models.DateTimeField(db_index=True)),
                ('refresh_expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('device_name', models.CharField(blank=True, max_length=128)),
                ('device_platform', models.CharField(blank=True, max_length=64)),
                ('app_version', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='native_app_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'last_used_at'], name='native_app_user_seen_idx'), models.Index(fields=['revoked_at', 'access_expires_at'], name='native_app_access_idx'), models.Index(fields=['revoked_at', 'refresh_expires_at'], name='native_app_refresh_idx')],
            },
        ),
    ]
