# Generated by Django 6.0 on 2026-04-07 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0335_add_user_trial_review_allows_trial_flag'),
        ('api', '0335_globalsecret'),
    ]

    operations = [
    ]
