# Generated by Django 6.0 on 2026-04-07 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0336_add_start_trial_capi_trial_eligibility_enforcement_flag'),
        ('api', '0336_merge_20260407_1603'),
    ]

    operations = [
    ]
