# Generated by Django 6.0 on 2026-04-08 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0337_globalagentskill_secrets_and_more'),
        ('api', '0339_evalsuiterun_launcher_type_and_launch_config'),
    ]

    operations = [
    ]
