# Generated by Django 6.0 on 2026-04-08 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0340_add_complete_registration_capi_trial_eligibility_flags'),
        ('api', '0340_merge_20260408_1455'),
    ]

    operations = [
    ]
