# Generated by Django 6.0 on 2026-04-08 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0341_videogenerationllmtier_videogenerationmodelendpoint_and_more'),
        ('api', '0342_add_stripe_checkout_context'),
    ]

    operations = [
    ]
