# Generated by Django 6.0 on 2026-04-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0345_add_user_trial_eligibility_one_per_user_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='browseruseagenttask',
            name='billing_is_trial',
            field=models.BooleanField(blank=True, help_text='Whether the billing owner was in trial when this task row was created.', null=True),
        ),
        migrations.AddField(
            model_name='browseruseagenttask',
            name='billing_plan',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('startup', 'Startup'), ('scale', 'Scale'), ('org_team', 'Team')], help_text='Billing plan snapshot when this task row was created.', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='persistentagentcompletion',
            name='billing_is_trial',
            field=models.BooleanField(blank=True, help_text='Whether the billing owner was in trial when this completion row was created.', null=True),
        ),
        migrations.AddField(
            model_name='persistentagentcompletion',
            name='billing_plan',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('startup', 'Startup'), ('scale', 'Scale'), ('org_team', 'Team')], help_text='Billing plan snapshot when this completion row was created.', max_length=32, null=True),
        ),
    ]
