# Generated by Django 6.0 on 2026-04-10 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0346_browseruseagenttask_billing_is_trial_and_more'),
        ('api', '0346_userflagdefinition_userflagassignment'),
    ]

    operations = [
    ]
