# Generated by Django 5.2 on 2026-04-13 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0347_merge_20260410_1925"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptconfig",
            name="internal_reasoning_history_limit",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="Maximum number of recent internal reasoning steps included in prompt context.",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
