# Generated by Django 5.2 on 2026-04-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0351_dailycreditconfig_default_daily_credit_target"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationbilling",
            name="execution_pause_resume_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When a customer-requested account pause is expected to resume, if known.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userbilling",
            name="execution_pause_resume_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When a customer-requested account pause is expected to resume, if known.",
                null=True,
            ),
        ),
    ]
