# Generated by Django 5.2 on 2026-04-15 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0351_dailycreditconfig_default_daily_credit_target"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promptconfig",
            name="browser_task_unified_history_limit",
        ),
    ]
