# Generated by Django 6.0 on 2026-04-15 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0352_remove_promptconfig_browser_task_unified_history_limit'),
        ('api', '0352_userbilling_execution_pause_resume_at_and_more'),
    ]

    operations = [
    ]
