# Generated by Django 5.2 on 2026-04-17 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0353_persistentagent_soft_delete_restore_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptconfig",
            name="max_skill_prompt_limit",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="Number of saved skills included in prompt context for max tier agents.",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="promptconfig",
            name="premium_skill_prompt_limit",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="Number of saved skills included in prompt context for premium tier agents.",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="promptconfig",
            name="standard_skill_prompt_limit",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="Number of saved skills included in prompt context for standard tier agents.",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="promptconfig",
            name="ultra_max_skill_prompt_limit",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="Number of saved skills included in prompt context for ultra max tier agents.",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="promptconfig",
            name="ultra_skill_prompt_limit",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="Number of saved skills included in prompt context for ultra tier agents.",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
