# Generated by Django 6.0 on 2026-04-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0353_persistentagent_soft_delete_restore_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolcreditcost",
            name="tier_exempt",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, the tier multiplier is not applied; users are charged the base credit cost regardless of LLM tier.",
            ),
        ),
    ]
