# Generated by Django 6.0 on 2026-04-19 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0347_add_user_fingerprint_visits'),
        ('api', '0355_add_cta_signup_modal_flag'),
    ]

    operations = [
    ]
