# Generated by Django 6.0 on 2026-04-17 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0353_merge_20260415_2134'),
        ('api', '0355_add_cta_signup_modal_flag'),
    ]

    operations = [
    ]
