# Generated by Django 6.0 on 2026-04-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0356_merge_20260419_1801"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfingerprintvisit",
            name="fingerprint_event_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Client-supplied Fingerprint request/event id used as the stable "
                    "dedupe key. The current JS integration sends the legacy requestId "
                    "value here."
                ),
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="userfingerprintvisit",
            name="fingerprint_server_event_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Canonical Fingerprint server event id returned by the server API.",
                max_length=255,
            ),
        ),
        migrations.AddIndex(
            model_name="userfingerprintvisit",
            index=models.Index(
                fields=["fingerprint_server_event_id"],
                name="finger_visit_srv_evt_idx",
            ),
        ),
    ]
