# Generated by Django 6.0 on 2026-04-22 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0356_persistent_agent_planning_mode'),
        ('api', '0357_add_user_fingerprint_server_event_id'),
    ]

    operations = [
    ]
