# Generated by Django 6.0 on 2026-04-29 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0362_persistentagentmessage_read_state'),
        ('api', '0362_useremail'),
    ]

    operations = [
    ]
