# Generated by Codex on 2026-05-01

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0363_merge_20260429_2023"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersistentAgentDashboard",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("created_by_agent", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard",
                        to="api.persistentagent",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="PersistentAgentDashboardWidget",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=160)),
                (
                    "widget_type",
                    models.CharField(
                        choices=[("metric", "Metric"), ("table", "Table"), ("bar", "Bar chart")],
                        max_length=24,
                    ),
                ),
                ("sql", models.TextField()),
                ("display_config", models.JSONField(blank=True, default=dict)),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="api.persistentagentdashboard",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="persistentagentdashboard",
            index=models.Index(fields=["agent", "-updated_at"], name="pa_dash_agent_updated_idx"),
        ),
        migrations.AddIndex(
            model_name="persistentagentdashboardwidget",
            index=models.Index(fields=["dashboard", "position"], name="pa_dash_widget_order_idx"),
        ),
    ]
