# Generated by Django 6.0 on 2026-05-03 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0360_add_scale_trial_checkout_switches'),
        ('api', '0366_user_flag_choice_groups'),
    ]

    operations = [
    ]
