# Generated by Django 6.0 on 2026-05-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0366_user_flag_choice_groups'),
        ('api', '0368_kanban_event_plan_deliverable_snapshots'),
    ]

    operations = [
    ]
