# Generated by Django 6.0 on 2026-05-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0367_add_agent_dashboards_flag'),
        ('api', '0369_merge_20260504_1158'),
    ]

    operations = [
    ]
