# Generated by Django 6.0 on 2026-05-06 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0356_merge_20260417_1752'),
        ('api', '0370_add_pricing_free_oss_plan_flag'),
    ]

    operations = [
    ]
