# Generated by Django 6.0 on 2026-05-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0372_persistentagenterror_created_at_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationbilling',
            name='execution_pause_reason',
            field=models.CharField(blank=True, choices=[('', '---------'), ('billing_delinquency', 'Billing delinquency'), ('trial_conversion_failed', 'Trial conversion failed'), ('trial_ended_non_renewal', 'Trial ended without renewal'), ('customer_account_pause', 'Customer account pause'), ('admin_manual_pause', 'Admin manual pause')], default='', help_text='Machine-readable reason for the current execution pause.', max_length=64),
        ),
        migrations.AlterField(
            model_name='userbilling',
            name='execution_pause_reason',
            field=models.CharField(blank=True, choices=[('', '---------'), ('billing_delinquency', 'Billing delinquency'), ('trial_conversion_failed', 'Trial conversion failed'), ('trial_ended_non_renewal', 'Trial ended without renewal'), ('customer_account_pause', 'Customer account pause'), ('admin_manual_pause', 'Admin manual pause')], default='', help_text='Machine-readable reason for the current execution pause.', max_length=64),
        ),
    ]
