# Generated by Django 6.0 on 2026-05-07 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0367_merge_20260503_1926'),
        ('api', '0373_alter_organizationbilling_execution_pause_reason_and_more'),
    ]

    operations = [
    ]
