# Generated by Codex on 2026-05-07

from django.db import migrations, models


EXECUTION_PAUSE_REASON_CHOICES = [
    ("", "---------"),
    ("billing_delinquency", "Billing delinquency"),
    ("trial_conversion_failed", "Trial conversion failed"),
    ("trial_ended_non_renewal", "Trial ended without renewal"),
    ("account_cancellation", "Account cancellation"),
    ("customer_account_pause", "Customer account pause"),
    ("admin_manual_pause", "Admin manual pause"),
]


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0374_merge_20260507_1850"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationbilling",
            name="execution_pause_reason",
            field=models.CharField(
                blank=True,
                choices=EXECUTION_PAUSE_REASON_CHOICES,
                default="",
                help_text="Machine-readable reason for the current execution pause.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="userbilling",
            name="execution_pause_reason",
            field=models.CharField(
                blank=True,
                choices=EXECUTION_PAUSE_REASON_CHOICES,
                default="",
                help_text="Machine-readable reason for the current execution pause.",
                max_length=64,
            ),
        ),
    ]
