# Generated by Django 6.0 on 2026-05-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0374_merge_20260507_1850'),
        ('api', '0374_pipedream_trigger_subscription'),
    ]

    operations = [
    ]
