# Generated by Django 6.0 on 2026-05-08 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0375_add_account_cancellation_execution_pause_reason'),
        ('api', '0375_merge_20260508_1645'),
    ]

    operations = [
    ]
