# Generated by Django 6.0 on 2026-05-09 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0376_merge_20260508_1822'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionPartner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_approved', models.BooleanField(db_index=True, default=False, help_text='Approved partners can access the Solutions Partner portal.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='managed_by_solution_partner',
            field=models.ForeignKey(blank=True, help_text='Solutions Partner that manages this client organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_organizations', to='api.solutionpartner'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='source_solution_partner',
            field=models.ForeignKey(blank=True, help_text='Set when this org access was granted through a Solutions Partner relationship.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to='api.solutionpartner'),
        ),
        migrations.CreateModel(
            name='SolutionPartnerMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='admin', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('solution_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.solutionpartner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_partner_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['solution_partner__name', 'user__email'],
                'unique_together': {('solution_partner', 'user')},
            },
        ),
    ]
