# Generated by Django 6.0 on 2026-05-09 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0367_add_agent_dashboards_flag'),
        ('api', '0376_merge_20260508_1822'),
    ]

    operations = [
    ]
