# Generated by Django 6.0 on 2026-05-11 15:42

from decimal import Decimal

from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0376_merge_20260508_1822"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailycreditconfig",
            name="burn_rate_threshold_24h",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                help_text="Preferred maximum rolling 24-hour credit burn before burn-rate controls apply. Set to 0 to disable.",
                max_digits=12,
                validators=[MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
