# Generated by Codex on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0377_dailycreditconfig_burn_rate_threshold_24h"),
    ]

    operations = [
        migrations.AddField(
            model_name="intelligencetier",
            name="blacklisted_tools",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "Tool function names that should be unavailable for agents running on this "
                    "intelligence tier. Examples: sqlite_batch, mcp_server_tool_name."
                ),
            ),
        ),
    ]
