# Generated by Django 6.0 on 2026-05-16 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0377_solutionpartner_and_more'),
        ('api', '0379_persistent_agent_judge_suggestion'),
    ]

    operations = [
    ]
