# Generated by Codex on 2026-05-18

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0382_persistentagentdiscordwebhookecho"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersistentAgentPlanCreditEstimate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                            ("stale", "Stale"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("none", "One-off"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly_or_other", "Monthly or Other"),
                        ],
                        default="none",
                        max_length=32,
                    ),
                ),
                (
                    "base_estimate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "actual_credits",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                ("actual_started_at", models.DateTimeField(blank=True, null=True)),
                ("actual_completed_at", models.DateTimeField(blank=True, null=True)),
                ("plan_snapshot", models.JSONField(blank=True, default=dict)),
                ("step_estimates", models.JSONField(blank=True, default=list)),
                ("tool_breakdown", models.JSONField(blank=True, default=list)),
                ("assumptions", models.JSONField(blank=True, default=list)),
                ("llm_model", models.CharField(blank=True, max_length=256)),
                ("llm_provider", models.CharField(blank=True, max_length=128)),
                ("error_message", models.TextField(blank=True)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_credit_estimates",
                        to="api.persistentagent",
                    ),
                ),
                (
                    "kanban_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_estimate",
                        to="api.persistentagentkanbanevent",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="persistentagentplancreditestimate",
            index=models.Index(fields=["agent", "status", "-created_at"], name="pa_plan_est_agent_status_idx"),
        ),
        migrations.AddIndex(
            model_name="persistentagentplancreditestimate",
            index=models.Index(fields=["agent", "-created_at"], name="pa_plan_est_agent_recent_idx"),
        ),
        migrations.AlterField(
            model_name="persistentagentcompletion",
            name="completion_type",
            field=models.CharField(
                choices=[
                    ("orchestrator", "Orchestrator"),
                    ("compaction", "Comms Compaction"),
                    ("step_compaction", "Step Compaction"),
                    ("tag", "Tag Generation"),
                    ("short_description", "Short Description"),
                    ("mini_description", "Mini Description"),
                    ("avatar_visual_description", "Avatar Visual Description"),
                    ("avatar_image_generation", "Avatar Image Generation"),
                    ("image_generation", "Image Generation"),
                    ("video_generation", "Video Generation"),
                    ("tool_search", "Tool Search"),
                    ("template_clone", "Template Clone"),
                    ("agent_chat_suggestion", "Agent Chat Suggestion"),
                    ("human_input_request_matching", "Human Input Request Matching"),
                    ("plan_credit_estimate", "Plan Credit Estimate"),
                    ("llm_judge", "LLM Judge"),
                    ("other", "Other"),
                ],
                default="orchestrator",
                help_text="Origin of the completion (orchestrator loop, compaction, tag generation, etc.).",
                max_length=64,
            ),
        ),
    ]
