# Generated by Django 6.0 on 2026-06-04 18:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0388_native_integration_secret_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtimeVoiceModelEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(help_text="Endpoint key, e.g., 'azure_realtime_default'", max_length=96, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('low_latency', models.BooleanField(default=True, help_text='Marks this endpoint as low latency/high performance.')),
                ('deployment', models.CharField(blank=True, help_text='Azure OpenAI Realtime deployment name.', max_length=256)),
                ('api_base', models.CharField(blank=True, help_text='Azure OpenAI resource endpoint, e.g. https://resource.openai.azure.com.', max_length=256)),
                ('voice', models.CharField(blank=True, default='marin', help_text='Default Realtime output voice.', max_length=64)),
                ('transcription_model', models.CharField(blank=True, default='gpt-4o-transcribe-latest', help_text='Realtime input transcription model used for transcript events.', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(blank=True, help_text='Provider supplying credentials for this Realtime endpoint.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realtime_voice_endpoints', to='api.llmprovider')),
            ],
            options={
                'ordering': ['provider__display_name', 'deployment'],
            },
        ),
        migrations.AddField(
            model_name='llmroutingprofile',
            name='voice_endpoint',
            field=models.ForeignKey(blank=True, help_text='Endpoint used for agent chat Realtime voice mode.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_profiles', to='api.realtimevoicemodelendpoint'),
        ),
        migrations.AddIndex(
            model_name='realtimevoicemodelendpoint',
            index=models.Index(fields=['key'], name='api_realtim_key_e15749_idx'),
        ),
        migrations.AddIndex(
            model_name='realtimevoicemodelendpoint',
            index=models.Index(fields=['enabled'], name='api_realtim_enabled_21a6b9_idx'),
        ),
        migrations.AddIndex(
            model_name='realtimevoicemodelendpoint',
            index=models.Index(fields=['provider'], name='api_realtim_provide_0274d4_idx'),
        ),
    ]
