# Generated by Django 6.0 on 2026-06-02 14:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0388_native_integration_secret_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentOrgChart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewport', models.JSONField(blank=True, default=dict)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agent_org_charts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_org_charts', to='api.organization')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_org_charts', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_agent_org_charts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentOrgChartEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='api.agentorgchart')),
                ('child_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_chart_parent_edges', to='api.persistentagent')),
                ('parent_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_chart_child_edges', to='api.persistentagent')),
                ('peer_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_chart_edges', to='api.agentpeerlink')),
            ],
        ),
        migrations.CreateModel(
            name='AgentOrgChartNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_chart_nodes', to='api.persistentagent')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='api.agentorgchart')),
            ],
        ),
        migrations.AddConstraint(
            model_name='agentorgchart',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', True), ('owner_user__isnull', False)), models.Q(('organization__isnull', False), ('owner_user__isnull', True)), _connector='OR'), name='agent_org_chart_one_owner_scope'),
        ),
        migrations.AddConstraint(
            model_name='agentorgchart',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True), ('owner_user__isnull', False)), fields=('owner_user',), name='unique_personal_agent_org_chart'),
        ),
        migrations.AddConstraint(
            model_name='agentorgchart',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', False), ('owner_user__isnull', True)), fields=('organization',), name='unique_org_agent_org_chart'),
        ),
        migrations.AddIndex(
            model_name='agentorgchartedge',
            index=models.Index(fields=['chart', 'parent_agent'], name='agent_org_edge_parent'),
        ),
        migrations.AddIndex(
            model_name='agentorgchartedge',
            index=models.Index(fields=['chart', 'child_agent'], name='agent_org_edge_child'),
        ),
        migrations.AddConstraint(
            model_name='agentorgchartedge',
            constraint=models.UniqueConstraint(fields=('chart', 'child_agent'), name='unique_agent_org_chart_child'),
        ),
        migrations.AddConstraint(
            model_name='agentorgchartedge',
            constraint=models.UniqueConstraint(fields=('chart', 'parent_agent', 'child_agent'), name='unique_agent_org_chart_edge'),
        ),
        migrations.AddConstraint(
            model_name='agentorgchartedge',
            constraint=models.UniqueConstraint(fields=('chart', 'peer_link'), name='unique_agent_org_chart_peer_link'),
        ),
        migrations.AddConstraint(
            model_name='agentorgchartedge',
            constraint=models.CheckConstraint(condition=models.Q(('parent_agent', models.F('child_agent')), _negated=True), name='agent_org_chart_no_self_edge'),
        ),
        migrations.AddIndex(
            model_name='agentorgchartnode',
            index=models.Index(fields=['chart', 'agent'], name='agent_org_node_lookup'),
        ),
        migrations.AddConstraint(
            model_name='agentorgchartnode',
            constraint=models.UniqueConstraint(fields=('chart', 'agent'), name='unique_agent_org_chart_node'),
        ),
    ]
