# Generated by Django 6.0 on 2026-06-08 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0390_repair_persistent_agent_template_url_alias_table'),
        ('api', '0391_persistentagenttemplate_description_markdown'),
    ]

    operations = [
    ]
