# Generated by Django 6.0 on 2026-06-08 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0390_rename_connected_app_channels_to_discord_native'),
        ('api', '0392_merge_20260608_1640'),
    ]

    operations = [
    ]
