# Generated by Django 6.0 on 2026-06-09 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0393_merge_20260608_1937'),
        ('api', '0393_persistentagenttemplate_seo_detail_fields'),
    ]

    operations = [
    ]
