# Generated by Django 6.0 on 2026-06-16 19:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0398_rename_file_str_replace_to_apply_patch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentallowlistinvite',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('slack', 'Slack'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('web', 'Web Chat'), ('other', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='agentcommpeerstate',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('slack', 'Slack'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('web', 'Web Chat'), ('other', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='commsallowlistentry',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('slack', 'Slack'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('web', 'Web Chat'), ('other', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='commsallowlistrequest',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('slack', 'Slack'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('web', 'Web Chat'), ('other', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='persistentagentcommsendpoint',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('slack', 'Slack'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('web', 'Web Chat'), ('other', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='persistentagentconversation',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('slack', 'Slack'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('web', 'Web Chat'), ('other', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='persistentagenthumaninputrequest',
            name='recipient_channel',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('sms', 'SMS'), ('slack', 'Slack'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('web', 'Web Chat'), ('other', 'Other')], help_text='Explicit recipient channel when the request targets a specific identity.', max_length=32),
        ),
        migrations.AlterField(
            model_name='persistentagenthumaninputrequest',
            name='requested_via_channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('slack', 'Slack'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('web', 'Web Chat'), ('other', 'Other')], max_length=32),
        ),
        migrations.CreateModel(
            name='PersistentAgentTelegramProvisioningSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suggested_username', models.CharField(max_length=64)),
                ('suggested_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('expired', 'Expired'), ('error', 'Error'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_provisioning_sessions', to='api.persistentagent')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_telegram_provisioning_sessions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_provisioning_sessions', to='api.organization')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_provisioning_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersistentAgentTelegramBotIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_bot_id', models.CharField(max_length=32, unique=True)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('token_encrypted', models.BinaryField(blank=True, null=True)),
                ('webhook_secret_encrypted', models.BinaryField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disconnected', 'Disconnected'), ('error', 'Error')], db_index=True, default='active', max_length=16)),
                ('profile_sync_status', models.CharField(choices=[('never', 'Never synced'), ('synced', 'Synced'), ('error', 'Error')], db_index=True, default='never', max_length=16)),
                ('profile_synced_at', models.DateTimeField(blank=True, null=True)),
                ('profile_sync_error', models.TextField(blank=True)),
                ('last_update_id', models.BigIntegerField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_bot_identity', to='api.persistentagent')),
                ('provisioning_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_identities', to='api.persistentagenttelegramprovisioningsession')),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='PersistentAgentTelegramUpdateReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('update_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_receipts', to='api.persistentagenttelegrambotidentity')),
            ],
            options={
                'ordering': ['-update_id'],
            },
        ),
        migrations.CreateModel(
            name='PersistentAgentTelegramUserLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_user_id', models.CharField(max_length=32)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_telegram_users', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_user_links', to='api.organization')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_user_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersistentAgentTelegramUserLinkRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_user_link_requests', to='api.persistentagent')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_telegram_user_link_requests', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_user_link_requests', to='api.organization')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_user_link_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', 'expires_at'], name='pa_tg_link_req_agent_idx'), models.Index(fields=['expires_at'], name='pa_tg_link_req_exp_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', True), ('owner_user__isnull', False)), models.Q(('organization__isnull', False), ('owner_user__isnull', True)), _connector='OR'), name='pa_tg_link_req_one_owner')],
            },
        ),
        migrations.AddField(
            model_name='persistentagenttelegramprovisioningsession',
            name='user_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisioning_sessions', to='api.persistentagenttelegramuserlink'),
        ),
        migrations.CreateModel(
            name='PersistentAgentTelegramChatBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_id', models.CharField(max_length=64)),
                ('chat_type', models.CharField(blank=True, max_length=32)),
                ('message_thread_id', models.CharField(blank=True, max_length=64)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('error', 'Error')], db_index=True, default='active', max_length=16)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_chat_bindings', to='api.persistentagent')),
                ('bot_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_bindings', to='api.persistentagenttelegrambotidentity')),
            ],
            options={
                'ordering': ['title', 'chat_id', 'message_thread_id'],
                'indexes': [models.Index(fields=['agent', 'status'], name='pa_tg_chat_agent_idx'), models.Index(fields=['bot_identity', 'chat_id'], name='pa_tg_chat_lookup_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('bot_identity', 'chat_id', 'message_thread_id'), name='uniq_active_tg_chat_binding')],
            },
        ),
        migrations.AddIndex(
            model_name='persistentagenttelegrambotidentity',
            index=models.Index(fields=['agent', 'status'], name='pa_tg_bot_agent_status_idx'),
        ),
        migrations.AddIndex(
            model_name='persistentagenttelegrambotidentity',
            index=models.Index(fields=['username'], name='pa_tg_bot_username_idx'),
        ),
        migrations.AddIndex(
            model_name='persistentagenttelegramupdatereceipt',
            index=models.Index(fields=['bot_identity', '-update_id'], name='pa_tg_update_bot_idx'),
        ),
        migrations.AddIndex(
            model_name='persistentagenttelegramupdatereceipt',
            index=models.Index(fields=['created_at'], name='pa_tg_update_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='persistentagenttelegramupdatereceipt',
            constraint=models.UniqueConstraint(fields=('bot_identity', 'update_id'), name='uniq_tg_bot_update_receipt'),
        ),
        migrations.AddIndex(
            model_name='persistentagenttelegramuserlink',
            index=models.Index(fields=['owner_user', 'is_active'], name='pa_tg_user_link_user_idx'),
        ),
        migrations.AddIndex(
            model_name='persistentagenttelegramuserlink',
            index=models.Index(fields=['organization', 'is_active'], name='pa_tg_user_link_org_idx'),
        ),
        migrations.AddIndex(
            model_name='persistentagenttelegramuserlink',
            index=models.Index(fields=['telegram_user_id'], name='pa_tg_user_link_tgid_idx'),
        ),
        migrations.AddConstraint(
            model_name='persistentagenttelegramuserlink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('organization__isnull', True)), fields=('owner_user', 'telegram_user_id'), name='uniq_active_tg_user_link_user'),
        ),
        migrations.AddConstraint(
            model_name='persistentagenttelegramuserlink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('owner_user__isnull', True)), fields=('organization', 'telegram_user_id'), name='uniq_active_tg_user_link_org'),
        ),
        migrations.AddConstraint(
            model_name='persistentagenttelegramuserlink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', True), ('owner_user__isnull', False)), models.Q(('organization__isnull', False), ('owner_user__isnull', True)), _connector='OR'), name='pa_tg_user_link_one_owner'),
        ),
        migrations.AddIndex(
            model_name='persistentagenttelegramprovisioningsession',
            index=models.Index(fields=['agent', 'status'], name='pa_tg_session_agent_idx'),
        ),
        migrations.AddIndex(
            model_name='persistentagenttelegramprovisioningsession',
            index=models.Index(fields=['user_link', 'status'], name='pa_tg_session_link_idx'),
        ),
        migrations.AddIndex(
            model_name='persistentagenttelegramprovisioningsession',
            index=models.Index(fields=['expires_at'], name='pa_tg_session_exp_idx'),
        ),
        migrations.AddConstraint(
            model_name='persistentagenttelegramprovisioningsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user_link',), name='uniq_pending_tg_session_link'),
        ),
        migrations.AddConstraint(
            model_name='persistentagenttelegramprovisioningsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', True), ('owner_user__isnull', False)), models.Q(('organization__isnull', False), ('owner_user__isnull', True)), _connector='OR'), name='pa_tg_session_one_owner'),
        ),
    ]
