# Generated by Django 6.0 on 2026-06-18 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0400_agent_owner_custom_instructions'),
        ('api', '0400_trialpromo_email_allowlist'),
    ]

    operations = [
    ]
