# Generated by Codex on 2026-06-25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0402_remove_agent_retry_completion_on_web_session_activation_switch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersistentAgentSlackWorkspace",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("team_id", models.CharField(max_length=32)),
                ("team_name", models.CharField(max_length=255)),
                ("enterprise_id", models.CharField(blank=True, max_length=64)),
                ("enterprise_name", models.CharField(blank=True, max_length=255)),
                ("app_id", models.CharField(blank=True, max_length=64)),
                ("bot_user_id", models.CharField(blank=True, max_length=64)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "claimed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claimed_slack_workspaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slack_workspace_claims",
                        to="api.organization",
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slack_workspace_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["team_name", "team_id"],
            },
        ),
        migrations.CreateModel(
            name="PersistentAgentSlackEventReceipt",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event_id", models.CharField(max_length=128, unique=True)),
                ("team_id", models.CharField(blank=True, max_length=64)),
                ("event_type", models.CharField(blank=True, max_length=64)),
                ("channel_id", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PersistentAgentSlackChannelSubscription",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("channel_id", models.CharField(max_length=32)),
                ("channel_name", models.CharField(blank=True, max_length=255)),
                ("channel_type", models.CharField(blank=True, max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("disabled", "Disabled"), ("error", "Error")],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slack_channel_subscriptions",
                        to="api.persistentagent",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_subscriptions",
                        to="api.persistentagentslackworkspace",
                    ),
                ),
            ],
            options={
                "ordering": ["workspace__team_name", "channel_name", "channel_id"],
            },
        ),
        migrations.AddIndex(
            model_name="persistentagentslackworkspace",
            index=models.Index(fields=["owner_user", "is_active"], name="pa_slack_ws_user_idx"),
        ),
        migrations.AddIndex(
            model_name="persistentagentslackworkspace",
            index=models.Index(fields=["organization", "is_active"], name="pa_slack_ws_org_idx"),
        ),
        migrations.AddIndex(
            model_name="persistentagentslackworkspace",
            index=models.Index(fields=["team_id"], name="pa_slack_ws_team_idx"),
        ),
        migrations.AddConstraint(
            model_name="persistentagentslackworkspace",
            constraint=models.UniqueConstraint(
                condition=Q(("is_active", True)),
                fields=("team_id",),
                name="uniq_active_slack_workspace_claim",
            ),
        ),
        migrations.AddConstraint(
            model_name="persistentagentslackworkspace",
            constraint=models.CheckConstraint(
                condition=(
                    Q(("owner_user__isnull", False), ("organization__isnull", True))
                    | Q(("owner_user__isnull", True), ("organization__isnull", False))
                ),
                name="pa_slack_workspace_one_owner",
            ),
        ),
        migrations.AddIndex(
            model_name="persistentagentslackeventreceipt",
            index=models.Index(fields=["team_id", "created_at"], name="pa_slack_evt_team_idx"),
        ),
        migrations.AddIndex(
            model_name="persistentagentslackeventreceipt",
            index=models.Index(fields=["channel_id", "created_at"], name="pa_slack_evt_channel_idx"),
        ),
        migrations.AddIndex(
            model_name="persistentagentslackchannelsubscription",
            index=models.Index(fields=["agent", "status"], name="pa_slack_sub_agent_idx"),
        ),
        migrations.AddIndex(
            model_name="persistentagentslackchannelsubscription",
            index=models.Index(fields=["workspace", "channel_id"], name="pa_slack_sub_channel_idx"),
        ),
        migrations.AddConstraint(
            model_name="persistentagentslackchannelsubscription",
            constraint=models.UniqueConstraint(
                condition=Q(("status", "active")),
                fields=("agent", "workspace", "channel_id"),
                name="uniq_active_slack_agent_channel_sub",
            ),
        ),
    ]
