# Generated by Codex on 2026-06-29

import re

from django.db import IntegrityError, migrations, transaction
from django.utils.crypto import get_random_string


def _build_base_username(name: str) -> str:
    base_username = (name or "").lower().strip()
    base_username = re.sub(r"\s+", ".", base_username)
    base_username = re.sub(r"[^\w.]", "", base_username)
    base_username = re.sub(r"\.+", ".", base_username)
    base_username = base_username.strip(".")
    if not base_username:
        base_username = "agent"
    return base_username


def _generate_unique_email_address(Endpoint, display_name: str, domain: str) -> str:
    base_username = _build_base_username(display_name)

    email_address = f"{base_username}@{domain}"
    if not Endpoint.objects.filter(channel="email", address__iexact=email_address).exists():
        return email_address

    for index in range(2, 100):
        email_address = f"{base_username}{index}@{domain}"
        if not Endpoint.objects.filter(channel="email", address__iexact=email_address).exists():
            return email_address

    random_suffix = get_random_string(4).lower()
    email_address = f"{base_username}-{random_suffix}@{domain}"
    if not Endpoint.objects.filter(channel="email", address__iexact=email_address).exists():
        return email_address

    raise RuntimeError("Unable to generate a unique email address for alias backfill.")


def backfill_non_deleted_default_agent_email_aliases(apps, schema_editor):
    from django.conf import settings

    if not settings.ENABLE_DEFAULT_AGENT_EMAIL:
        return

    domain = (settings.DEFAULT_AGENT_EMAIL_DOMAIN or "").strip().lower()
    if not domain:
        return

    suffix = f"@{domain}"
    Agent = apps.get_model("api", "PersistentAgent")
    Endpoint = apps.get_model("api", "PersistentAgentCommsEndpoint")
    EmailMeta = apps.get_model("api", "PersistentAgentEmailEndpoint")

    agents = (
        Agent.objects
        .filter(is_deleted=False)
        .exclude(execution_environment="eval")
        .values_list("id", "name")
        .iterator(chunk_size=500)
    )

    for agent_id, agent_name in agents:
        with transaction.atomic():
            display_name = (agent_name or "").strip() or "Agent"
            existing_endpoint = Endpoint.objects.filter(
                channel="email",
                owner_agent_id=agent_id,
                address__iendswith=suffix,
            ).first()
            if existing_endpoint is not None:
                EmailMeta.objects.get_or_create(
                    endpoint_id=existing_endpoint.id,
                    defaults={
                        "display_name": display_name,
                        "verified": True,
                    },
                )
                continue

            is_primary = not Endpoint.objects.filter(
                channel="email",
                owner_agent_id=agent_id,
                is_primary=True,
            ).exists()

            endpoint = None
            for _ in range(3):
                try:
                    with transaction.atomic():
                        email_address = _generate_unique_email_address(
                            Endpoint,
                            display_name=display_name,
                            domain=domain,
                        )
                        endpoint = Endpoint.objects.create(
                            owner_agent_id=agent_id,
                            channel="email",
                            address=email_address.lower(),
                            is_primary=is_primary,
                        )
                    break
                except IntegrityError:
                    continue

            if endpoint is None:
                continue

            EmailMeta.objects.get_or_create(
                endpoint_id=endpoint.id,
                defaults={
                    "display_name": display_name,
                    "verified": True,
                },
            )


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("api", "0403_remove_agent_colors"),
    ]

    operations = [
        migrations.RunPython(
            backfill_non_deleted_default_agent_email_aliases,
            reverse_code=migrations.RunPython.noop,
            atomic=False,
        ),
    ]
