# Generated by Codex on 2026-06-29

from django.db import migrations


BRIGHTDATA_MCP_ARGS = ["-y", "@brightdata/mcp@2.11.0"]


def update_brightdata_mcp_version(apps, schema_editor):
    MCPServerConfig = apps.get_model("api", "MCPServerConfig")
    MCPServerConfig.objects.filter(
        scope="platform",
        name="brightdata",
    ).update(
        command="npx",
        command_args=BRIGHTDATA_MCP_ARGS,
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0404_backfill_non_deleted_default_agent_email_aliases"),
    ]

    operations = [
        migrations.RunPython(update_brightdata_mcp_version, noop_reverse),
    ]
