# Generated by Django 6.0 on 2026-07-02 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0407_persistentagenttemplate_preferred_llm_tier'),
        ('api', '0407_remove_always_on_waffle_rows'),
    ]

    operations = [
    ]
