# Generated by Django 6.0 on 2026-07-02 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0406_update_org_team_credits_per_seat'),
        ('api', '0408_merge_20260702_1615'),
    ]

    operations = [
    ]
