# Generated by Django 6.0 on 2026-07-03 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0406_userbilling_scheduled_customer_pause'),
        ('api', '0409_merge_20260702_1712'),
    ]

    operations = [
    ]
