# Generated by Django 6.0 on 2026-07-06 14:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0410_migrate_meta_ads_profiles_to_native_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentagenttemplate',
            name='hide_related_templates',
            field=models.BooleanField(default=False, help_text='Hide the related templates section on the public detail page.'),
        ),
        migrations.AddField(
            model_name='persistentagenttemplate',
            name='hide_tools',
            field=models.BooleanField(default=False, help_text='Hide tool-related badges, lists, and detail sections on the public detail page.'),
        ),
        migrations.CreateModel(
            name='PersistentAgentTemplateRelatedTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first on the public detail page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specified_as_related_template_links', to='api.persistentagenttemplate')),
                ('source_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specified_related_template_links', to='api.persistentagenttemplate')),
            ],
            options={
                'ordering': ['source_template', 'position', 'related_template'],
            },
        ),
        migrations.AddField(
            model_name='persistentagenttemplate',
            name='specified_related_templates',
            field=models.ManyToManyField(blank=True, help_text='Manually ordered related templates for the public detail page.', related_name='specified_by_templates', through='api.PersistentAgentTemplateRelatedTemplate', through_fields=('source_template', 'related_template'), to='api.persistentagenttemplate'),
        ),
        migrations.AddIndex(
            model_name='persistentagenttemplaterelatedtemplate',
            index=models.Index(fields=['source_template', 'position'], name='pat_rel_src_pos_idx'),
        ),
        migrations.AddIndex(
            model_name='persistentagenttemplaterelatedtemplate',
            index=models.Index(fields=['related_template'], name='pat_rel_target_idx'),
        ),
        migrations.AddConstraint(
            model_name='persistentagenttemplaterelatedtemplate',
            constraint=models.UniqueConstraint(fields=('source_template', 'related_template'), name='uniq_pat_rel_pair'),
        ),
        migrations.AddConstraint(
            model_name='persistentagenttemplaterelatedtemplate',
            constraint=models.CheckConstraint(condition=models.Q(('source_template_id', models.F('related_template_id')), _negated=True), name='pat_rel_not_self'),
        ),
    ]
