# Generated by Django 6.0 on 2026-07-06 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0411_persistent_agent_template_public_options'),
        ('api', '0411_template_url_alias_legacy_handle'),
    ]

    operations = [
    ]
