# Generated by Django 6.0 on 2026-07-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0411_persistent_agent_template_public_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persistentagentsystemmessage',
            name='body',
            field=models.TextField(help_text="System directive text delivered into the agent's unified history."),
        ),
        migrations.AlterField(
            model_name='persistentagentsystemmessage',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text="Timestamp when this directive was delivered into the agent's unified history.", null=True),
        ),
        migrations.AlterField(
            model_name='persistentagentsystemmessage',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Disable to keep the record but skip delivery into unified history.'),
        ),
    ]
