# Generated by Django 6.0 on 2026-07-07 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0413_product_announcements'),
        ('api', '0414_persistentagenttemplate_social_image'),
    ]

    operations = [
    ]
