# Generated by Django 6.0 on 2026-07-08 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0413_agent_credit_forecasts'),
        ('api', '0415_merge_20260707_2003'),
    ]

    operations = [
    ]
