# Generated by Django 6.0 on 2026-07-08 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0415_merge_20260707_2003'),
        ('api', '0415_persistentagenttemplate_social_image_public_storage'),
    ]

    operations = [
    ]
