# Generated by Django 6.0 on 2026-07-08 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0413_agent_credit_forecasts'),
        ('api', '0416_merge_20260708_1356'),
    ]

    operations = [
    ]
