# Generated by Django 6.0 on 2026-07-09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0416_merge_20260708_1356"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersistentAgentUserActionEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("human_input_answered", "Human Input Answered"),
                            ("human_input_dismissed", "Human Input Dismissed"),
                            ("secrets_saved", "Secrets Saved"),
                            ("secrets_removed", "Secrets Removed"),
                            ("contacts_approved", "Contacts Approved"),
                            ("contacts_declined", "Contacts Declined"),
                            ("contacts_resolved", "Contacts Resolved"),
                        ],
                        max_length=64,
                    ),
                ),
                ("count", models.PositiveIntegerField(default=1)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="persistent_agent_action_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_action_events",
                        to="api.persistentagent",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
                "indexes": [
                    models.Index(fields=["agent", "-occurred_at"], name="pa_action_agent_recent_idx"),
                    models.Index(fields=["agent", "action_type", "-occurred_at"], name="pa_action_agent_type_idx"),
                ],
            },
        ),
    ]
