# Generated by Django 6.0 on 2026-07-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0422_intelligencetier_trial_default'),
        ('api', '0422_update_pretrained_employee_descriptions'),
    ]

    operations = [
    ]
