# Generated by Django 6.0 on 2026-07-17 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0426_persistentagenttoolcall_display_metadata'),
        ('api', '0427_add_contact_auto_approve_email_flag'),
    ]

    operations = [
    ]
