# Generated by Django 6.0 on 2026-07-18 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0412_merge_20260706_1628'),
        ('api', '0428_merge_20260717_1758'),
    ]

    operations = [
    ]
