# Generated by Django 6.0 on 2026-07-20

import django.db.models.deletion
import uuid

from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


def backfill_email_sending_modes(apps, schema_editor):
    PersistentAgent = apps.get_model("api", "PersistentAgent")
    PersistentAgent.objects.filter(contact_approval_mode="auto_approve_email").update(
        email_sending_mode="send_automatically"
    )
    PersistentAgent.objects.exclude(contact_approval_mode="auto_approve_email").update(
        email_sending_mode="review_new_contacts"
    )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0429_merge_20260718_1400"),
    ]

    operations = [
        migrations.AddField(
            model_name="persistentagent",
            name="email_sending_mode",
            field=models.CharField(
                choices=[
                    ("review_all_external", "Review before send"),
                    ("review_new_contacts", "Review only new contacts"),
                    ("send_automatically", "Send automatically"),
                ],
                default="review_all_external",
                help_text="Requested email sending mode. Organization policy may enforce a stricter effective mode.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="persistentagentmessageattachment",
            name="content_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="outboundmessageattempt",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_approval", "Pending approval"),
                    ("queued", "Queued"),
                    ("sending", "Sending"),
                    ("sent", "Sent to provider"),
                    ("delivered", "Delivered"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="persistentagentmessage",
            name="latest_status",
            field=models.CharField(
                choices=[
                    ("pending_approval", "Pending approval"),
                    ("queued", "Queued"),
                    ("sending", "Sending"),
                    ("sent", "Sent to provider"),
                    ("delivered", "Delivered"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="queued",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="persistentagentuseractionevent",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("human_input_answered", "Human Input Answered"),
                    ("human_input_dismissed", "Human Input Dismissed"),
                    ("secrets_saved", "Secrets Saved"),
                    ("secrets_removed", "Secrets Removed"),
                    ("contacts_approved", "Contacts Approved"),
                    ("contacts_declined", "Contacts Declined"),
                    ("contacts_resolved", "Contacts Resolved"),
                    ("outbox_edited", "Outbox email edited"),
                    ("outbox_approved", "Outbox email approved"),
                    ("outbox_discarded", "Outbox email discarded"),
                    ("outbox_expired", "Outbox email expired"),
                    ("outbox_failed", "Outbox email failed"),
                    ("outbox_retried", "Outbox email retried"),
                ],
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="OutboundEmailReview",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("discarded", "Discarded"), ("expired", "Expired")], db_index=True, default="pending", max_length=16)),
                ("content_version", models.PositiveIntegerField(default=1)),
                ("content_hash", models.CharField(max_length=64)),
                ("approved_version", models.PositiveIntegerField(blank=True, null=True)),
                ("approved_content_hash", models.CharField(blank=True, max_length=64)),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("last_edited_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("agent", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="outbound_email_reviews", to="api.persistentagent")),
                ("decided_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="outbox_items_decided", to=settings.AUTH_USER_MODEL)),
                ("last_edited_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="outbox_items_edited", to=settings.AUTH_USER_MODEL)),
                ("message", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="outbound_email_review", to="api.persistentagentmessage")),
            ],
            options={
                "ordering": ["-queued_at", "-id"],
                "indexes": [
                    models.Index(fields=["agent", "status", "-queued_at"], name="outbox_agent_status_idx"),
                    models.Index(fields=["status", "expires_at"], name="outbox_status_expiry_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OutboundEmailReviewNotificationState",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("pending_cycle_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_digest_sent_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="outbox_notification_state", to="api.organization")),
                ("user", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="outbox_notification_state", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=(Q(("organization__isnull", True), ("user__isnull", False)) | Q(("organization__isnull", False), ("user__isnull", True))),
                        name="outbox_notification_exactly_one_workspace",
                    ),
                ],
            },
        ),
        migrations.RunPython(backfill_email_sending_modes, migrations.RunPython.noop),
    ]
