# Generated by Django 6.0 on 2026-07-20 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0429_merge_20260718_1400'),
        ('api', '0429_persistentagentlinkreference_public_id'),
    ]

    operations = [
    ]
