# Generated by Django 6.0 on 2026-07-21 10:10

import api.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0429_merge_20260718_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persistentagenttemplateurlalias',
            options={'ordering': ['handle', 'slug']},
        ),
        migrations.CreateModel(
            name='PersistentAgentLinkReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=api.models.generate_link_reference_public_id, editable=False, max_length=17, unique=True)),
                ('url', models.TextField()),
                ('url_hash', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_references', to='api.persistentagent')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('agent', 'url_hash'), name='unique_agent_link_url_hash')],
            },
        ),
    ]
