# Generated by Django 6.0 on 2026-07-21 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0430_email_review_outbox'),
        ('api', '0430_persistentagentlinkreference'),
    ]

    operations = [
    ]
