# Generated by Django 6.0 on 2026-07-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0431_enable_discord_reaction_tool'),
        ('api', '0431_merge_20260721_2230'),
    ]

    operations = [
    ]
