# Generated by Django 6.0 on 2026-07-22

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0431_enable_discord_reaction_tool"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersistentAgentSchedule",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "schedule_key",
                    models.CharField(
                        help_text="Stable agent-scoped identifier used when updating this schedule.",
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use lowercase letters, numbers, underscores, or hyphens.",
                                regex="^[a-z0-9][a-z0-9_-]{0,63}$",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "instruction",
                    models.CharField(
                        blank=True,
                        help_text="What the agent should do when this schedule fires.",
                        max_length=500,
                    ),
                ),
                ("kind", models.CharField(choices=[("recurring", "Recurring"), ("once", "One time")], max_length=16)),
                (
                    "expression",
                    models.CharField(
                        blank=True,
                        help_text="Cron or @every expression for a recurring schedule.",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="IANA timezone used to interpret recurring cron expressions.",
                        max_length=64,
                    ),
                ),
                (
                    "run_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Exact timezone-aware instant for a one-time schedule.",
                        null=True,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_fired_at", models.DateTimeField(blank=True, null=True)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_schedules",
                        to="api.persistentagent",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "schedule_key"],
                "indexes": [
                    models.Index(fields=["agent", "enabled", "next_run_at"], name="pa_sched_agent_due_idx"),
                    models.Index(fields=["enabled", "next_run_at"], name="pa_sched_due_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("agent", "schedule_key"), name="unique_agent_schedule_key"),
                    models.CheckConstraint(
                        condition=(
                            models.Q(("expression__isnull", False), ("kind", "recurring"), ("run_at__isnull", True))
                            | models.Q(("expression__isnull", True), ("kind", "once"), ("run_at__isnull", False))
                        ),
                        name="agent_schedule_kind_payload",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("schedule_key", "primary"), _negated=True),
                        name="agent_schedule_key_not_primary",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="persistentagentcrontrigger",
            name="occurrence_key",
            field=models.CharField(
                blank=True,
                help_text="Idempotency key for a concrete scheduled occurrence.",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="persistentagentcrontrigger",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trigger_events",
                to="api.persistentagentschedule",
            ),
        ),
        migrations.AddField(
            model_name="persistentagentcrontrigger",
            name="schedule_instruction",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="persistentagentcrontrigger",
            name="schedule_key",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="persistentagentcrontrigger",
            name="schedule_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="persistentagentcrontrigger",
            name="scheduled_for",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="persistentagentcrontrigger",
            index=models.Index(fields=["scheduled_for"], name="pa_cron_scheduled_idx"),
        ),
    ]
