# Generated by Django 6.0 on 2026-07-22 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0432_merge_20260722_1347'),
        ('api', '0433_persistent_agent_emotion'),
    ]

    operations = [
    ]
