# Generated by Django 6.0 on 2026-07-24 23:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0434_persistentagenttoolcall_queued_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelegatedSecureValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
                ('encrypted_value', models.BinaryField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('consumption_destination', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_by_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_secure_values', to='api.persistentagent')),
                ('source_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegated_secure_values', to='api.persistentagent')),
            ],
            options={
                'indexes': [models.Index(fields=['source_agent', 'expires_at'], name='dsv_source_expires_idx')],
            },
        ),
    ]
