# Generated by Django 6.0 on 2026-07-27 11:27

import api.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0437_retire_mandatory_planning_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('spritesheet', models.FileField(max_length=512, upload_to=api.models.user_pet_spritesheet_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User pet',
                'verbose_name_plural': 'User pets',
                'ordering': ('display_name', 'created_at'),
            },
        ),
    ]
