# Generated by Django 6.0 on 2026-07-27 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0434_merge_20260722_1745'),
        ('api', '0439_persistentagentmessage_body_search'),
    ]

    operations = [
    ]
