# Generated by Django 6.0 on 2026-07-29 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0442_discord_explicit_guild_authorization"),
        ("api", "0442_retire_pretrained_worker_pages"),
    ]

    operations = []
