# Generated by Django 6.0 on 2026-07-29 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0442_transparent_trial_promos'),
        ('api', '0443_merge_20260729_1737'),
    ]

    operations = [
    ]
