# Generated by Django 6.0 on 2026-07-29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0443_merge_20260729_1737"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersistentAgentMCPTask",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("server_name", models.CharField(max_length=64)),
                ("remote_task_id", models.CharField(max_length=512)),
                ("tool_name", models.CharField(max_length=256)),
                ("remote_tool_name", models.CharField(max_length=256)),
                ("tool_arguments", models.JSONField(default=dict)),
                ("protocol_version", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("working", "Working"),
                            ("input_required", "Input required"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="working",
                        max_length=32,
                    ),
                ),
                ("status_message", models.TextField(blank=True)),
                ("input_requests", models.JSONField(blank=True, null=True)),
                ("result", models.JSONField(blank=True, null=True)),
                ("error", models.JSONField(blank=True, null=True)),
                ("poll_interval_ms", models.PositiveIntegerField(default=2000)),
                ("next_poll_at", models.DateTimeField(blank=True, null=True)),
                ("deadline_at", models.DateTimeField()),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("lease_token", models.UUIDField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("budget_id", models.CharField(blank=True, max_length=100)),
                ("branch_id", models.CharField(blank=True, max_length=100)),
                ("depth", models.PositiveIntegerField(blank=True, null=True)),
                ("eval_run_id", models.UUIDField(blank=True, null=True)),
                ("wake_enqueued_at", models.DateTimeField(blank=True, null=True)),
                ("terminal_at", models.DateTimeField(blank=True, null=True)),
                ("remote_created_at", models.DateTimeField(blank=True, null=True)),
                ("remote_updated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_tasks",
                        to="api.persistentagent",
                    ),
                ),
                (
                    "originating_tool_call",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mcp_tasks",
                        to="api.persistentagenttoolcall",
                    ),
                ),
                (
                    "server_config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_tasks",
                        to="api.mcpserverconfig",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["agent", "status"], name="mcp_task_agent_status_idx"),
                    models.Index(fields=["status", "next_poll_at"], name="mcp_task_status_poll_idx"),
                    models.Index(fields=["lease_expires_at"], name="mcp_task_lease_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("server_config", "remote_task_id"),
                        name="unique_mcp_remote_task_per_server",
                    ),
                ],
            },
        ),
    ]
