# Generated by Django 6.0 on 2026-07-30 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0444_merge_20260729_1916'),
        ('api', '0444_persistentagentmcptask'),
    ]

    operations = [
    ]
