# Generated by Django 6.0 on 2026-07-30 13:10

from django.db import migrations, models
from django.utils import timezone


def resolve_delivered_judge_suggestions(apps, schema_editor):
    suggestion_model = apps.get_model("api", "PersistentAgentJudgeSuggestion")
    delivered_suggestions = suggestion_model.objects.filter(
        status="active",
        system_message__delivered_at__isnull=False,
    )
    delivered_suggestions.filter(resolved_at__isnull=True).update(
        status="delivered",
        resolved_at=timezone.now(),
    )
    delivered_suggestions.update(status="delivered")


def restore_delivered_judge_suggestions(apps, schema_editor):
    suggestion_model = apps.get_model("api", "PersistentAgentJudgeSuggestion")
    suggestion_model.objects.filter(status="delivered").update(status="active")


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0444_persistentagentmcptask"),
    ]

    operations = [
        migrations.AddField(
            model_name="persistentagentmessage",
            name="bcc_endpoints",
            field=models.ManyToManyField(
                blank=True,
                help_text="Hidden recipients for outbound email",
                related_name="bcc_messages",
                to="api.persistentagentcommsendpoint",
            ),
        ),
        migrations.AlterField(
            model_name="persistentagentjudgesuggestion",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_review", "Pending Review"),
                    ("active", "Active"),
                    ("delivered", "Delivered"),
                    ("dismissed", "Dismissed"),
                ],
                db_index=True,
                default="active",
                max_length=16,
            ),
        ),
        migrations.RunPython(
            resolve_delivered_judge_suggestions,
            restore_delivered_judge_suggestions,
        ),
    ]
