# Generated by Django 6.0 on 2026-07-30 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0445_judge_lifecycle_and_email_bcc'),
        ('api', '0445_merge_20260730_1303'),
    ]

    operations = [
    ]
