# Generated by Django 6.0 on 2026-07-31 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0446_computer_cpp_integration'),
        ('api', '0446_merge_20260730_2207'),
    ]

    operations = [
    ]
