# Generated by Django 6.0 on 2026-08-03

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


GOOGLE_PROVIDER_KEY = "google_drive"
GOOGLE_SECRET_KEYS = ("native_google_drive", "native_google_sheets")
INTEGRATION_DOMAIN_SENTINEL = "__gobii_integration__"


def backfill_google_routing_locks(apps, _schema_editor):
    GlobalSecret = apps.get_model("api", "GlobalSecret")
    RoutingLock = apps.get_model("api", "NativeIntegrationRoutingLock")
    secrets = GlobalSecret.objects.filter(
        secret_type="integration",
        domain_pattern=INTEGRATION_DOMAIN_SENTINEL,
        key__in=GOOGLE_SECRET_KEYS,
    ).values("user_id", "organization_id")

    seen = set()
    locks = []
    for secret in secrets.iterator():
        owner_key = (secret["user_id"], secret["organization_id"])
        if owner_key in seen:
            continue
        seen.add(owner_key)
        locks.append(
            RoutingLock(
                user_id=secret["user_id"],
                organization_id=secret["organization_id"],
                provider_key=GOOGLE_PROVIDER_KEY,
            )
        )
    RoutingLock.objects.bulk_create(locks, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0449_visible_agent_message_roster_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NativeIntegrationRoutingLock",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider_key", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="native_integration_routing_locks",
                        to="api.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="native_integration_routing_locks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["organization", "provider_key"], name="native_route_lock_org_idx"),
                    models.Index(fields=["user", "provider_key"], name="native_route_lock_user_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=(
                            models.Q(("organization__isnull", False), ("user__isnull", True))
                            | models.Q(("organization__isnull", True), ("user__isnull", False))
                        ),
                        name="native_route_lock_one_owner",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("organization__isnull", False)),
                        fields=("organization", "provider_key"),
                        name="unique_native_route_lock_org",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", False)),
                        fields=("user", "provider_key"),
                        name="unique_native_route_lock_user",
                    ),
                ],
            },
        ),
        migrations.RunPython(backfill_google_routing_locks, migrations.RunPython.noop),
    ]
