# Generated by Django 6.0 on 2026-08-06 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0450_decouple_contact_approval_from_outbox'),
        ('api', '0451_disable_pipedream_google_sheets_guard_by_default'),
    ]

    operations = [
    ]
