# Generated by Django 6.0 on 2026-08-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0452_merge_20260806_1634'),
        ('api', '0452_persistentagenttemplate_no_index'),
    ]

    operations = [
    ]
