# Generated by Django 6.0 on 2026-08-08 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0452_add_contactout_pilot_flag'),
        ('api', '0454_default_new_workspaces_to_automatic_email'),
    ]

    operations = [
    ]
