# Generated by Django 6.0 on 2026-08-11 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0446_managed_mcp_integrations'),
        ('api', '0456_add_pipedream_apollo_guard_switch'),
    ]

    operations = [
    ]
