# Generated by Django 6.0 on 2026-08-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0458_portable_agent_exports'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortableAgentExportArtifactCleanup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.CharField(max_length=512, unique=True)),
                ('source_export_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
