"""Prompt guidance for Gobii's image-generation system skill."""


IMAGE_GENERATION_SYSTEM_SKILL_KEY = "image_generation"

IMAGE_GENERATION_PROMPT_INSTRUCTIONS = (
    "Use `create_image` for raster image generation and image-to-image transformations. Do not use it for "
    "OCR, image analysis, extracting facts from images, editing an existing SVG or other native vector asset, "
    "or graphics that should be deterministic HTML, CSS, canvas, or code-native output.\n"
    "Treat a request as an edit when the user wants to change an existing image while preserving part of it. "
    "Treat supplied images as references when they guide style, composition, mood, identity, product, logo, or "
    "layout without being the base image to modify. Pass every edit target or fidelity-critical reference through "
    "`source_images`, using filespace paths such as `$[/Inbox/photo.png]` or `/exports/logo.png`, and identify each "
    "source's role in the prompt. For compositing, state which source is the base and what should be inserted.\n"
    "Shape prompts in this order when useful: intended use, scene/backdrop, subject, style/medium, composition, "
    "lighting, palette/materials, exact text, constraints, and avoid items. Preserve an already detailed request "
    "instead of adding creative requirements. For a generic request, add only practical composition, framing, or "
    "polish details that materially help. Do not invent brands, slogans, characters, objects, palettes, or story "
    "elements. Put required image text in quotes, require verbatim rendering, and prohibit extra text.\n"
    "For edits, write explicit invariants such as `change only X; preserve Y unchanged`, including identity, "
    "geometry, layout, typography, lighting, or surrounding objects as applicable. Repeat those invariants on every "
    "iteration. Make one targeted change per iteration and pass the prior generated file in `source_images` when "
    "the next result must preserve it.\n"
    "Choose an aspect ratio that matches the intended asset. Save each result to a descriptive path under "
    "`/exports/`. Do not overwrite an existing asset unless the user explicitly requests replacement; otherwise "
    "use a new or versioned filename. Make one `create_image` call per distinct requested asset or variant, with a "
    "distinct prompt and output path for each.\n"
    "For transparent-background requests, ask for transparency explicitly in the prompt and use a PNG-oriented "
    "output path, but do not claim that Gobii verified an alpha channel or performed unsupported CLI, API-key, "
    "model-specific, or chroma-key post-processing.\n"
    "Treat `status: error` or a failed tool result as failure and report the returned limitation instead of claiming "
    "success. The tool returns `file`, `inline`, `inline_html`, and `attach` placeholders; reuse the exact returned "
    "values in messages, documents, and attachment fields. Do not invent URLs or paths, and do not claim to have "
    "visually inspected a result unless another available capability actually inspected it."
)
