name: Preview Image + Notify

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

concurrency:
  # Use PR number from the triggering CI run
  group: preview-image-${{ github.event.workflow_run.pull_requests[0].number }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  build-and-dispatch:
    name: Build image and notify infra
    runs-on: ubuntu-latest
    # Only run when CI succeeded, for PR-triggered runs, and for trusted authors
    if: >-
      ${{ github.event.workflow_run.conclusion == 'success' &&
          github.event.workflow_run.event == 'pull_request' &&
          (
            github.event.workflow_run.pull_requests[0].author_association == 'OWNER' ||
            github.event.workflow_run.pull_requests[0].author_association == 'MEMBER' ||
            github.event.workflow_run.pull_requests[0].author_association == 'COLLABORATOR' ||
            github.event.workflow_run.pull_requests[0].head.repo.full_name == github.repository
          )
      }}
    steps:
      - name: Checkout PR head commit
        uses: actions/checkout@v4
        with:
          # Ensure we build from the exact PR head commit, not the merge commit
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push PR image (head SHA)
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            ghcr.io/gobii-ai/gobii-platform:sha-${{ github.event.workflow_run.head_sha }}
            ghcr.io/gobii-ai/gobii-platform:pr-${{ github.event.workflow_run.pull_requests[0].number }}
          # Keep it single-arch for speed
          platforms: linux/amd64
          provenance: false
          sbom: false
          cache-from: type=gha,scope=gobii-platform
          cache-to: type=gha,mode=max,scope=gobii-platform

      - name: Generate GitHub App token
        id: app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          installation_retrieval_mode: repository
          installation_retrieval_payload: gobii-ai/gobii

      - name: Trigger infra preview deploy
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: gobii-ai/gobii
          event-type: preview-deploy
          client-payload: |
            {
              "owner": "${{ github.repository_owner }}",
              "repo": "${{ github.event.repository.name }}",
              "pr_number": ${{ github.event.workflow_run.pull_requests[0].number }},
              "head_sha": "${{ github.event.workflow_run.head_sha }}",
              "image_tag": "sha-${{ github.event.workflow_run.head_sha }}",
              "html_url": "https://github.com/${{ github.repository }}/pull/${{ github.event.workflow_run.pull_requests[0].number }}"
            }
