name: Preview Image + Notify

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: preview-image-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  build-and-dispatch:
    name: Build image and notify infra
    runs-on: ubuntu-latest
    # Only run for trusted authors (org OWNER or MEMBER)
    if: |
      github.event.pull_request.author_association == 'OWNER' ||
      github.event.pull_request.author_association == 'MEMBER' ||
      github.event.pull_request.author_association == 'COLLABORATOR'
    steps:
      - name: Checkout PR head commit
        uses: actions/checkout@v4
        with:
          # Ensure we build from the exact PR head commit, not the merge commit
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute short SHA
        id: vars
        run: echo "short_sha=$(echo \"$PR_HEAD_SHA\" | cut -c1-7)" >> "$GITHUB_OUTPUT"
        env:
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}

      - name: Build and push PR image (head SHA)
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            ghcr.io/gobii-ai/gobii-platform:sha-${{ github.event.pull_request.head.sha }}
            ghcr.io/gobii-ai/gobii-platform:sha-${{ steps.vars.outputs.short_sha }}
            ghcr.io/gobii-ai/gobii-platform:pr-${{ github.event.pull_request.number }}
          # Keep it single-arch for speed
          platforms: linux/amd64
          provenance: false
          sbom: false
          cache-from: type=gha,scope=gobii-platform
          cache-to: type=gha,mode=max,scope=gobii-platform

      - name: Generate GitHub App token
        id: app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          installation_retrieval_mode: repository
          installation_retrieval_payload: gobii-ai/gobii

      - name: Trigger infra preview deploy
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: gobii-ai/gobii
          event-type: preview-deploy
          client-payload: |
            {
              "owner": "${{ github.repository_owner }}",
              "repo": "${{ github.event.repository.name }}",
              "pr_number": ${{ github.event.pull_request.number }},
              "head_sha": "${{ github.event.pull_request.head.sha }}",
              "image_tag": "sha-${{ steps.vars.outputs.short_sha }}",
              "html_url": "${{ github.event.pull_request.html_url }}"
            }
