name: Preview Image + Notify

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: preview-image-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  debug-context:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Print PR context
        run: |
          echo "author_association=${{ github.event.pull_request.author_association }}"
          echo "is_fork=${{ github.event.pull_request.head.repo.fork }}"
          echo "head_repo=${{ github.event.pull_request.head.repo.full_name }}"
          echo "base_repo=${{ github.event.pull_request.base.repo.full_name }}"
  build-and-dispatch:
    name: Build image and notify infra
    runs-on: ubuntu-latest
    # Only run for trusted authors (org OWNER or MEMBER)
    if: |
      github.event.pull_request.author_association == 'OWNER' ||
      github.event.pull_request.author_association == 'MEMBER'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push PR image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            ghcr.io/gobii-ai/gobii-platform:sha-${{ github.sha }}
            ghcr.io/gobii-ai/gobii-platform:pr-${{ github.event.pull_request.number }}
          # Keep it single-arch for speed
          platforms: linux/amd64
          provenance: false
          sbom: false
          cache-from: type=gha,scope=gobii-platform
          cache-to: type=gha,mode=max,scope=gobii-platform

      - name: Generate GitHub App token
        id: app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          installation_retrieval_mode: repository
          installation_retrieval_payload: gobii-ai/gobii

      - name: Trigger infra preview deploy
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: gobii-ai/gobii
          event-type: preview-deploy
          client-payload: |
            {
              "owner": "${{ github.repository_owner }}",
              "repo": "${{ github.event.repository.name }}",
              "pr_number": ${{ github.event.pull_request.number }},
              "head_sha": "${{ github.sha }}",
              "image_tag": "sha-${{ github.sha }}",
              "html_url": "${{ github.event.pull_request.html_url }}"
            }
